/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv400CreateUserCustomerLinksRequestProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv400CreateUserCustomerLinksRequestProperties{}

// OBPv400CreateUserCustomerLinksRequestProperties struct for OBPv400CreateUserCustomerLinksRequestProperties
type OBPv400CreateUserCustomerLinksRequestProperties struct {
	CustomerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"customer_id"`
	UserId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"user_id"`
}

type _OBPv400CreateUserCustomerLinksRequestProperties OBPv400CreateUserCustomerLinksRequestProperties

// NewOBPv400CreateUserCustomerLinksRequestProperties instantiates a new OBPv400CreateUserCustomerLinksRequestProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv400CreateUserCustomerLinksRequestProperties(customerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, userId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv400CreateUserCustomerLinksRequestProperties {
	this := OBPv400CreateUserCustomerLinksRequestProperties{}
	this.CustomerId = customerId
	this.UserId = userId
	return &this
}

// NewOBPv400CreateUserCustomerLinksRequestPropertiesWithDefaults instantiates a new OBPv400CreateUserCustomerLinksRequestProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv400CreateUserCustomerLinksRequestPropertiesWithDefaults() *OBPv400CreateUserCustomerLinksRequestProperties {
	this := OBPv400CreateUserCustomerLinksRequestProperties{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *OBPv400CreateUserCustomerLinksRequestProperties) GetCustomerId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *OBPv400CreateUserCustomerLinksRequestProperties) GetCustomerIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *OBPv400CreateUserCustomerLinksRequestProperties) SetCustomerId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CustomerId = v
}

// GetUserId returns the UserId field value
func (o *OBPv400CreateUserCustomerLinksRequestProperties) GetUserId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *OBPv400CreateUserCustomerLinksRequestProperties) GetUserIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *OBPv400CreateUserCustomerLinksRequestProperties) SetUserId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.UserId = v
}

func (o OBPv400CreateUserCustomerLinksRequestProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv400CreateUserCustomerLinksRequestProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *OBPv400CreateUserCustomerLinksRequestProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv400CreateUserCustomerLinksRequestProperties := _OBPv400CreateUserCustomerLinksRequestProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv400CreateUserCustomerLinksRequestProperties)

	if err != nil {
		return err
	}

	*o = OBPv400CreateUserCustomerLinksRequestProperties(varOBPv400CreateUserCustomerLinksRequestProperties)

	return err
}

type NullableOBPv400CreateUserCustomerLinksRequestProperties struct {
	value *OBPv400CreateUserCustomerLinksRequestProperties
	isSet bool
}

func (v NullableOBPv400CreateUserCustomerLinksRequestProperties) Get() *OBPv400CreateUserCustomerLinksRequestProperties {
	return v.value
}

func (v *NullableOBPv400CreateUserCustomerLinksRequestProperties) Set(val *OBPv400CreateUserCustomerLinksRequestProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv400CreateUserCustomerLinksRequestProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv400CreateUserCustomerLinksRequestProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv400CreateUserCustomerLinksRequestProperties(val *OBPv400CreateUserCustomerLinksRequestProperties) *NullableOBPv400CreateUserCustomerLinksRequestProperties {
	return &NullableOBPv400CreateUserCustomerLinksRequestProperties{value: val, isSet: true}
}

func (v NullableOBPv400CreateUserCustomerLinksRequestProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv400CreateUserCustomerLinksRequestProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


