/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties{}

// OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties struct for OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties
type OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties struct {
	NationalIdentifier OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"national_identifier"`
	Name OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"name"`
}

type _OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties

// NewOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties instantiates a new OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties(nationalIdentifier OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, name OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties {
	this := OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties{}
	this.NationalIdentifier = nationalIdentifier
	this.Name = name
	return &this
}

// NewOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankPropertiesWithDefaults instantiates a new OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankPropertiesWithDefaults() *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties {
	this := OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties{}
	return &this
}

// GetNationalIdentifier returns the NationalIdentifier field value
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) GetNationalIdentifier() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.NationalIdentifier
}

// GetNationalIdentifierOk returns a tuple with the NationalIdentifier field value
// and a boolean to check if the value has been set.
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) GetNationalIdentifierOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NationalIdentifier, true
}

// SetNationalIdentifier sets field value
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) SetNationalIdentifier(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.NationalIdentifier = v
}

// GetName returns the Name field value
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) GetName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) GetNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) SetName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Name = v
}

func (o OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["national_identifier"] = o.NationalIdentifier
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"national_identifier",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties := _OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties)

	if err != nil {
		return err
	}

	*o = OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties(varOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties)

	return err
}

type NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties struct {
	value *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties
	isSet bool
}

func (v NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) Get() *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties {
	return v.value
}

func (v *NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) Set(val *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties(val *OBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) *NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties {
	return &NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties{value: val, isSet: true}
}

func (v NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv121GetOtherAccountForTransaction200ResponsePropertiesBankProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


