/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems{}

// OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems struct for OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems
type OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems struct {
	Type string `json:"type"`
	Properties OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties `json:"properties"`
}

type _OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems

// NewOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems instantiates a new OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems(type_ string, properties OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties) *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems {
	this := OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsWithDefaults instantiates a new OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsWithDefaults() *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems {
	this := OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems{}
	return &this
}

// GetType returns the Type field value
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) GetProperties() OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties {
	if o == nil {
		var ret OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) GetPropertiesOk() (*OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) SetProperties(v OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItemsProperties) {
	o.Properties = v
}

func (o OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems := _OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems)

	if err != nil {
		return err
	}

	*o = OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems(varOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems)

	return err
}

type NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems struct {
	value *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems
	isSet bool
}

func (v NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) Get() *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems {
	return v.value
}

func (v *NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) Set(val *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems(val *OBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) *NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems {
	return &NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems{value: val, isSet: true}
}

func (v NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv300GetPublicAccountById200ResponsePropertiesAccountRulesItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


