/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties{}

// OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties struct for OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties
type OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties struct {
	Description OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"description"`
	ShortCode OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"short_code"`
	BankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"bank_id"`
	Id OBPv400DeleteSystemLevelEndpointTag200Response `json:"id"`
	Charge OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit `json:"charge"`
	Summary OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"summary"`
}

type _OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties

// NewOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties instantiates a new OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties(description OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, shortCode OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, id OBPv400DeleteSystemLevelEndpointTag200Response, charge OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit, summary OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties {
	this := OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties{}
	this.Description = description
	this.ShortCode = shortCode
	this.BankId = bankId
	this.Id = id
	this.Charge = charge
	this.Summary = summary
	return &this
}

// NewOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsPropertiesWithDefaults instantiates a new OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsPropertiesWithDefaults() *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties {
	this := OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties{}
	return &this
}

// GetDescription returns the Description field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetDescription() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetDescriptionOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetDescription(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Description = v
}

// GetShortCode returns the ShortCode field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetShortCode() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetShortCodeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShortCode, true
}

// SetShortCode sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetShortCode(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ShortCode = v
}

// GetBankId returns the BankId field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetBankId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetBankIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetBankId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.BankId = v
}

// GetId returns the Id field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetId() OBPv400DeleteSystemLevelEndpointTag200Response {
	if o == nil {
		var ret OBPv400DeleteSystemLevelEndpointTag200Response
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetIdOk() (*OBPv400DeleteSystemLevelEndpointTag200Response, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetId(v OBPv400DeleteSystemLevelEndpointTag200Response) {
	o.Id = v
}

// GetCharge returns the Charge field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetCharge() OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit {
	if o == nil {
		var ret OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit
		return ret
	}

	return o.Charge
}

// GetChargeOk returns a tuple with the Charge field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetChargeOk() (*OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Charge, true
}

// SetCharge sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetCharge(v OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit) {
	o.Charge = v
}

// GetSummary returns the Summary field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetSummary() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) GetSummaryOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) SetSummary(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Summary = v
}

func (o OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["short_code"] = o.ShortCode
	toSerialize["bank_id"] = o.BankId
	toSerialize["id"] = o.Id
	toSerialize["charge"] = o.Charge
	toSerialize["summary"] = o.Summary
	return toSerialize, nil
}

func (o *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"short_code",
		"bank_id",
		"id",
		"charge",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties := _OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties)

	if err != nil {
		return err
	}

	*o = OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties(varOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties)

	return err
}

type NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties struct {
	value *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties
	isSet bool
}

func (v NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) Get() *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties {
	return v.value
}

func (v *NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) Set(val *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties(val *OBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) *NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties {
	return &NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties{value: val, isSet: true}
}

func (v NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv200GetTransactionTypes200ResponsePropertiesTransactionTypesItemsProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


