/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks{}

// OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks struct for OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks
type OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks struct {
	Type string `json:"type"`
	Items OBPv310EnableDisableAccountWebhook200Response `json:"items"`
}

type _OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks

// NewOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks instantiates a new OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks(type_ string, items OBPv310EnableDisableAccountWebhook200Response) *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks {
	this := OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks{}
	this.Type = type_
	this.Items = items
	return &this
}

// NewOBPv310GetAccountWebhooks200ResponsePropertiesWebHooksWithDefaults instantiates a new OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv310GetAccountWebhooks200ResponsePropertiesWebHooksWithDefaults() *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks {
	this := OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks{}
	return &this
}

// GetType returns the Type field value
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) SetType(v string) {
	o.Type = v
}

// GetItems returns the Items field value
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) GetItems() OBPv310EnableDisableAccountWebhook200Response {
	if o == nil {
		var ret OBPv310EnableDisableAccountWebhook200Response
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) GetItemsOk() (*OBPv310EnableDisableAccountWebhook200Response, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) SetItems(v OBPv310EnableDisableAccountWebhook200Response) {
	o.Items = v
}

func (o OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks := _OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks)

	if err != nil {
		return err
	}

	*o = OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks(varOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks)

	return err
}

type NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks struct {
	value *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks
	isSet bool
}

func (v NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) Get() *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks {
	return v.value
}

func (v *NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) Set(val *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks(val *OBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) *NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks {
	return &NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks{value: val, isSet: true}
}

func (v NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv310GetAccountWebhooks200ResponsePropertiesWebHooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


