/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv510UpdateConsumerRedirectURLRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv510UpdateConsumerRedirectURLRequest{}

// OBPv510UpdateConsumerRedirectURLRequest struct for OBPv510UpdateConsumerRedirectURLRequest
type OBPv510UpdateConsumerRedirectURLRequest struct {
	Type string `json:"type"`
	Properties OBPv510UpdateConsumerRedirectURLRequestProperties `json:"properties"`
}

type _OBPv510UpdateConsumerRedirectURLRequest OBPv510UpdateConsumerRedirectURLRequest

// NewOBPv510UpdateConsumerRedirectURLRequest instantiates a new OBPv510UpdateConsumerRedirectURLRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv510UpdateConsumerRedirectURLRequest(type_ string, properties OBPv510UpdateConsumerRedirectURLRequestProperties) *OBPv510UpdateConsumerRedirectURLRequest {
	this := OBPv510UpdateConsumerRedirectURLRequest{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewOBPv510UpdateConsumerRedirectURLRequestWithDefaults instantiates a new OBPv510UpdateConsumerRedirectURLRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv510UpdateConsumerRedirectURLRequestWithDefaults() *OBPv510UpdateConsumerRedirectURLRequest {
	this := OBPv510UpdateConsumerRedirectURLRequest{}
	return &this
}

// GetType returns the Type field value
func (o *OBPv510UpdateConsumerRedirectURLRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerRedirectURLRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OBPv510UpdateConsumerRedirectURLRequest) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *OBPv510UpdateConsumerRedirectURLRequest) GetProperties() OBPv510UpdateConsumerRedirectURLRequestProperties {
	if o == nil {
		var ret OBPv510UpdateConsumerRedirectURLRequestProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerRedirectURLRequest) GetPropertiesOk() (*OBPv510UpdateConsumerRedirectURLRequestProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *OBPv510UpdateConsumerRedirectURLRequest) SetProperties(v OBPv510UpdateConsumerRedirectURLRequestProperties) {
	o.Properties = v
}

func (o OBPv510UpdateConsumerRedirectURLRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv510UpdateConsumerRedirectURLRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *OBPv510UpdateConsumerRedirectURLRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv510UpdateConsumerRedirectURLRequest := _OBPv510UpdateConsumerRedirectURLRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv510UpdateConsumerRedirectURLRequest)

	if err != nil {
		return err
	}

	*o = OBPv510UpdateConsumerRedirectURLRequest(varOBPv510UpdateConsumerRedirectURLRequest)

	return err
}

type NullableOBPv510UpdateConsumerRedirectURLRequest struct {
	value *OBPv510UpdateConsumerRedirectURLRequest
	isSet bool
}

func (v NullableOBPv510UpdateConsumerRedirectURLRequest) Get() *OBPv510UpdateConsumerRedirectURLRequest {
	return v.value
}

func (v *NullableOBPv510UpdateConsumerRedirectURLRequest) Set(val *OBPv510UpdateConsumerRedirectURLRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv510UpdateConsumerRedirectURLRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv510UpdateConsumerRedirectURLRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv510UpdateConsumerRedirectURLRequest(val *OBPv510UpdateConsumerRedirectURLRequest) *NullableOBPv510UpdateConsumerRedirectURLRequest {
	return &NullableOBPv510UpdateConsumerRedirectURLRequest{value: val, isSet: true}
}

func (v NullableOBPv510UpdateConsumerRedirectURLRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv510UpdateConsumerRedirectURLRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


