/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties{}

// OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties struct for OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties
type OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties struct {
	OtherAccountRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_account_routing_address"`
	OtherAccountRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_account_routing_scheme"`
	CreatedByUserId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"created_by_user_id"`
	Name OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"name"`
	OtherAccountSecondaryRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_account_secondary_routing_address"`
	IsBeneficiary OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"is_beneficiary"`
	Description OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"description"`
	OtherBranchRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_branch_routing_address"`
	Bespoke OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke `json:"bespoke"`
	OtherBankRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_bank_routing_scheme"`
	OtherBranchRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_branch_routing_scheme"`
	ThisAccountId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"this_account_id"`
	ThisViewId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"this_view_id"`
	Currency OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"currency"`
	OtherBankRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_bank_routing_address"`
	ThisBankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"this_bank_id"`
	CounterpartyId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"counterparty_id"`
	OtherAccountSecondaryRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"other_account_secondary_routing_scheme"`
}

type _OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties

// NewOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties instantiates a new OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties(otherAccountRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherAccountRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, createdByUserId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, name OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherAccountSecondaryRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, isBeneficiary OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, description OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherBranchRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bespoke OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke, otherBankRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherBranchRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, thisAccountId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, thisViewId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, currency OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherBankRoutingAddress OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, thisBankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, counterpartyId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, otherAccountSecondaryRoutingScheme OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties {
	this := OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties{}
	this.OtherAccountRoutingAddress = otherAccountRoutingAddress
	this.OtherAccountRoutingScheme = otherAccountRoutingScheme
	this.CreatedByUserId = createdByUserId
	this.Name = name
	this.OtherAccountSecondaryRoutingAddress = otherAccountSecondaryRoutingAddress
	this.IsBeneficiary = isBeneficiary
	this.Description = description
	this.OtherBranchRoutingAddress = otherBranchRoutingAddress
	this.Bespoke = bespoke
	this.OtherBankRoutingScheme = otherBankRoutingScheme
	this.OtherBranchRoutingScheme = otherBranchRoutingScheme
	this.ThisAccountId = thisAccountId
	this.ThisViewId = thisViewId
	this.Currency = currency
	this.OtherBankRoutingAddress = otherBankRoutingAddress
	this.ThisBankId = thisBankId
	this.CounterpartyId = counterpartyId
	this.OtherAccountSecondaryRoutingScheme = otherAccountSecondaryRoutingScheme
	return &this
}

// NewOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsPropertiesWithDefaults instantiates a new OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsPropertiesWithDefaults() *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties {
	this := OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties{}
	return &this
}

// GetOtherAccountRoutingAddress returns the OtherAccountRoutingAddress field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountRoutingAddress() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherAccountRoutingAddress
}

// GetOtherAccountRoutingAddressOk returns a tuple with the OtherAccountRoutingAddress field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountRoutingAddressOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherAccountRoutingAddress, true
}

// SetOtherAccountRoutingAddress sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherAccountRoutingAddress(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherAccountRoutingAddress = v
}

// GetOtherAccountRoutingScheme returns the OtherAccountRoutingScheme field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountRoutingScheme() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherAccountRoutingScheme
}

// GetOtherAccountRoutingSchemeOk returns a tuple with the OtherAccountRoutingScheme field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountRoutingSchemeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherAccountRoutingScheme, true
}

// SetOtherAccountRoutingScheme sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherAccountRoutingScheme(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherAccountRoutingScheme = v
}

// GetCreatedByUserId returns the CreatedByUserId field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCreatedByUserId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCreatedByUserIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByUserId, true
}

// SetCreatedByUserId sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetCreatedByUserId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CreatedByUserId = v
}

// GetName returns the Name field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Name = v
}

// GetOtherAccountSecondaryRoutingAddress returns the OtherAccountSecondaryRoutingAddress field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountSecondaryRoutingAddress() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherAccountSecondaryRoutingAddress
}

// GetOtherAccountSecondaryRoutingAddressOk returns a tuple with the OtherAccountSecondaryRoutingAddress field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountSecondaryRoutingAddressOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherAccountSecondaryRoutingAddress, true
}

// SetOtherAccountSecondaryRoutingAddress sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherAccountSecondaryRoutingAddress(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherAccountSecondaryRoutingAddress = v
}

// GetIsBeneficiary returns the IsBeneficiary field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetIsBeneficiary() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.IsBeneficiary
}

// GetIsBeneficiaryOk returns a tuple with the IsBeneficiary field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetIsBeneficiaryOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBeneficiary, true
}

// SetIsBeneficiary sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetIsBeneficiary(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.IsBeneficiary = v
}

// GetDescription returns the Description field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetDescription() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetDescriptionOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetDescription(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Description = v
}

// GetOtherBranchRoutingAddress returns the OtherBranchRoutingAddress field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBranchRoutingAddress() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherBranchRoutingAddress
}

// GetOtherBranchRoutingAddressOk returns a tuple with the OtherBranchRoutingAddress field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBranchRoutingAddressOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherBranchRoutingAddress, true
}

// SetOtherBranchRoutingAddress sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherBranchRoutingAddress(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherBranchRoutingAddress = v
}

// GetBespoke returns the Bespoke field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetBespoke() OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke {
	if o == nil {
		var ret OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke
		return ret
	}

	return o.Bespoke
}

// GetBespokeOk returns a tuple with the Bespoke field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetBespokeOk() (*OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bespoke, true
}

// SetBespoke sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetBespoke(v OBPv400GetExplicitCounterpartyById200ResponsePropertiesBespoke) {
	o.Bespoke = v
}

// GetOtherBankRoutingScheme returns the OtherBankRoutingScheme field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBankRoutingScheme() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherBankRoutingScheme
}

// GetOtherBankRoutingSchemeOk returns a tuple with the OtherBankRoutingScheme field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBankRoutingSchemeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherBankRoutingScheme, true
}

// SetOtherBankRoutingScheme sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherBankRoutingScheme(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherBankRoutingScheme = v
}

// GetOtherBranchRoutingScheme returns the OtherBranchRoutingScheme field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBranchRoutingScheme() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherBranchRoutingScheme
}

// GetOtherBranchRoutingSchemeOk returns a tuple with the OtherBranchRoutingScheme field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBranchRoutingSchemeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherBranchRoutingScheme, true
}

// SetOtherBranchRoutingScheme sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherBranchRoutingScheme(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherBranchRoutingScheme = v
}

// GetThisAccountId returns the ThisAccountId field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisAccountId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ThisAccountId
}

// GetThisAccountIdOk returns a tuple with the ThisAccountId field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisAccountIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThisAccountId, true
}

// SetThisAccountId sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetThisAccountId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ThisAccountId = v
}

// GetThisViewId returns the ThisViewId field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisViewId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ThisViewId
}

// GetThisViewIdOk returns a tuple with the ThisViewId field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisViewIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThisViewId, true
}

// SetThisViewId sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetThisViewId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ThisViewId = v
}

// GetCurrency returns the Currency field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCurrency() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCurrencyOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetCurrency(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Currency = v
}

// GetOtherBankRoutingAddress returns the OtherBankRoutingAddress field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBankRoutingAddress() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherBankRoutingAddress
}

// GetOtherBankRoutingAddressOk returns a tuple with the OtherBankRoutingAddress field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherBankRoutingAddressOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherBankRoutingAddress, true
}

// SetOtherBankRoutingAddress sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherBankRoutingAddress(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherBankRoutingAddress = v
}

// GetThisBankId returns the ThisBankId field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisBankId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ThisBankId
}

// GetThisBankIdOk returns a tuple with the ThisBankId field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetThisBankIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThisBankId, true
}

// SetThisBankId sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetThisBankId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ThisBankId = v
}

// GetCounterpartyId returns the CounterpartyId field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCounterpartyId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CounterpartyId
}

// GetCounterpartyIdOk returns a tuple with the CounterpartyId field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetCounterpartyIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CounterpartyId, true
}

// SetCounterpartyId sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetCounterpartyId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CounterpartyId = v
}

// GetOtherAccountSecondaryRoutingScheme returns the OtherAccountSecondaryRoutingScheme field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountSecondaryRoutingScheme() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OtherAccountSecondaryRoutingScheme
}

// GetOtherAccountSecondaryRoutingSchemeOk returns a tuple with the OtherAccountSecondaryRoutingScheme field value
// and a boolean to check if the value has been set.
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) GetOtherAccountSecondaryRoutingSchemeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherAccountSecondaryRoutingScheme, true
}

// SetOtherAccountSecondaryRoutingScheme sets field value
func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) SetOtherAccountSecondaryRoutingScheme(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OtherAccountSecondaryRoutingScheme = v
}

func (o OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["other_account_routing_address"] = o.OtherAccountRoutingAddress
	toSerialize["other_account_routing_scheme"] = o.OtherAccountRoutingScheme
	toSerialize["created_by_user_id"] = o.CreatedByUserId
	toSerialize["name"] = o.Name
	toSerialize["other_account_secondary_routing_address"] = o.OtherAccountSecondaryRoutingAddress
	toSerialize["is_beneficiary"] = o.IsBeneficiary
	toSerialize["description"] = o.Description
	toSerialize["other_branch_routing_address"] = o.OtherBranchRoutingAddress
	toSerialize["bespoke"] = o.Bespoke
	toSerialize["other_bank_routing_scheme"] = o.OtherBankRoutingScheme
	toSerialize["other_branch_routing_scheme"] = o.OtherBranchRoutingScheme
	toSerialize["this_account_id"] = o.ThisAccountId
	toSerialize["this_view_id"] = o.ThisViewId
	toSerialize["currency"] = o.Currency
	toSerialize["other_bank_routing_address"] = o.OtherBankRoutingAddress
	toSerialize["this_bank_id"] = o.ThisBankId
	toSerialize["counterparty_id"] = o.CounterpartyId
	toSerialize["other_account_secondary_routing_scheme"] = o.OtherAccountSecondaryRoutingScheme
	return toSerialize, nil
}

func (o *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"other_account_routing_address",
		"other_account_routing_scheme",
		"created_by_user_id",
		"name",
		"other_account_secondary_routing_address",
		"is_beneficiary",
		"description",
		"other_branch_routing_address",
		"bespoke",
		"other_bank_routing_scheme",
		"other_branch_routing_scheme",
		"this_account_id",
		"this_view_id",
		"currency",
		"other_bank_routing_address",
		"this_bank_id",
		"counterparty_id",
		"other_account_secondary_routing_scheme",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties := _OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties)

	if err != nil {
		return err
	}

	*o = OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties(varOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties)

	return err
}

type NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties struct {
	value *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties
	isSet bool
}

func (v NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) Get() *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties {
	return v.value
}

func (v *NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) Set(val *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties(val *OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) *NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties {
	return &NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties{value: val, isSet: true}
}

func (v NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItemsProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


