/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties{}

// OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties struct for OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties
type OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties struct {
	CustomerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"customer_id"`
	CustomerAccountLinkId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"customer_account_link_id"`
	BankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"bank_id"`
	AccountId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"account_id"`
	RelationshipType OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"relationship_type"`
}

type _OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties

// NewOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties instantiates a new OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties(customerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, customerAccountLinkId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bankId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, accountId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, relationshipType OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties {
	this := OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties{}
	this.CustomerId = customerId
	this.CustomerAccountLinkId = customerAccountLinkId
	this.BankId = bankId
	this.AccountId = accountId
	this.RelationshipType = relationshipType
	return &this
}

// NewOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsPropertiesWithDefaults instantiates a new OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsPropertiesWithDefaults() *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties {
	this := OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetCustomerId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetCustomerIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) SetCustomerId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CustomerId = v
}

// GetCustomerAccountLinkId returns the CustomerAccountLinkId field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetCustomerAccountLinkId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CustomerAccountLinkId
}

// GetCustomerAccountLinkIdOk returns a tuple with the CustomerAccountLinkId field value
// and a boolean to check if the value has been set.
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetCustomerAccountLinkIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerAccountLinkId, true
}

// SetCustomerAccountLinkId sets field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) SetCustomerAccountLinkId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CustomerAccountLinkId = v
}

// GetBankId returns the BankId field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetBankId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetBankIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) SetBankId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.BankId = v
}

// GetAccountId returns the AccountId field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetAccountId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetAccountIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) SetAccountId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.AccountId = v
}

// GetRelationshipType returns the RelationshipType field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetRelationshipType() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value
// and a boolean to check if the value has been set.
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) GetRelationshipTypeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelationshipType, true
}

// SetRelationshipType sets field value
func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) SetRelationshipType(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.RelationshipType = v
}

func (o OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["customer_account_link_id"] = o.CustomerAccountLinkId
	toSerialize["bank_id"] = o.BankId
	toSerialize["account_id"] = o.AccountId
	toSerialize["relationship_type"] = o.RelationshipType
	return toSerialize, nil
}

func (o *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
		"customer_account_link_id",
		"bank_id",
		"account_id",
		"relationship_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties := _OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties)

	if err != nil {
		return err
	}

	*o = OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties(varOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties)

	return err
}

type NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties struct {
	value *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties
	isSet bool
}

func (v NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) Get() *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties {
	return v.value
}

func (v *NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) Set(val *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties(val *OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) *NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties {
	return &NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties{value: val, isSet: true}
}

func (v NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinksItemsProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


