/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties{}

// OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties struct for OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties
type OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties struct {
	SubjectDomainName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"subject_domain_name"`
	NotBefore OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"not_before"`
	RolesInfo OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"roles_info"`
	IssuerDomainName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"issuer_domain_name"`
	NotAfter OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"not_after"`
}

type _OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties

// NewOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties instantiates a new OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties(subjectDomainName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, notBefore OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, rolesInfo OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, issuerDomainName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, notAfter OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties {
	this := OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties{}
	this.SubjectDomainName = subjectDomainName
	this.NotBefore = notBefore
	this.RolesInfo = rolesInfo
	this.IssuerDomainName = issuerDomainName
	this.NotAfter = notAfter
	return &this
}

// NewOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoPropertiesWithDefaults instantiates a new OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoPropertiesWithDefaults() *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties {
	this := OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties{}
	return &this
}

// GetSubjectDomainName returns the SubjectDomainName field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetSubjectDomainName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.SubjectDomainName
}

// GetSubjectDomainNameOk returns a tuple with the SubjectDomainName field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetSubjectDomainNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectDomainName, true
}

// SetSubjectDomainName sets field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) SetSubjectDomainName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.SubjectDomainName = v
}

// GetNotBefore returns the NotBefore field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetNotBefore() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.NotBefore
}

// GetNotBeforeOk returns a tuple with the NotBefore field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetNotBeforeOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotBefore, true
}

// SetNotBefore sets field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) SetNotBefore(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.NotBefore = v
}

// GetRolesInfo returns the RolesInfo field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetRolesInfo() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.RolesInfo
}

// GetRolesInfoOk returns a tuple with the RolesInfo field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetRolesInfoOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolesInfo, true
}

// SetRolesInfo sets field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) SetRolesInfo(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.RolesInfo = v
}

// GetIssuerDomainName returns the IssuerDomainName field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetIssuerDomainName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.IssuerDomainName
}

// GetIssuerDomainNameOk returns a tuple with the IssuerDomainName field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetIssuerDomainNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerDomainName, true
}

// SetIssuerDomainName sets field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) SetIssuerDomainName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.IssuerDomainName = v
}

// GetNotAfter returns the NotAfter field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetNotAfter() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.NotAfter
}

// GetNotAfterOk returns a tuple with the NotAfter field value
// and a boolean to check if the value has been set.
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) GetNotAfterOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotAfter, true
}

// SetNotAfter sets field value
func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) SetNotAfter(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.NotAfter = v
}

func (o OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject_domain_name"] = o.SubjectDomainName
	toSerialize["not_before"] = o.NotBefore
	toSerialize["roles_info"] = o.RolesInfo
	toSerialize["issuer_domain_name"] = o.IssuerDomainName
	toSerialize["not_after"] = o.NotAfter
	return toSerialize, nil
}

func (o *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject_domain_name",
		"not_before",
		"roles_info",
		"issuer_domain_name",
		"not_after",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties := _OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties)

	if err != nil {
		return err
	}

	*o = OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties(varOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties)

	return err
}

type NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties struct {
	value *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties
	isSet bool
}

func (v NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) Get() *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties {
	return v.value
}

func (v *NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) Set(val *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties(val *OBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) *NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties {
	return &NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties{value: val, isSet: true}
}

func (v NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv510UpdateConsumerName200ResponsePropertiesCertificateInfoProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


