/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties{}

// OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties struct for OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties
type OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties struct {
	Duration OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"duration"`
	ResponseBody OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody `json:"response_body"`
	ImplementedInVersion OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"implemented_in_version"`
	TargetIp OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"target_ip"`
	Url OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"url"`
	CorrelationId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"correlation_id"`
	ImplementedByPartialFunction OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"implemented_by_partial_function"`
	UserId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"user_id"`
	DeveloperEmail OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"developer_email"`
	Date OBPv600UpdateRateLimitsRequestPropertiesFromDate `json:"date"`
	ConsumerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"consumer_id"`
	OperationId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"operation_id"`
	Verb OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"verb"`
	AppName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"app_name"`
	SourceIp OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"source_ip"`
	UserName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName `json:"user_name"`
}

type _OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties

// NewOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties instantiates a new OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties(duration OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, responseBody OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody, implementedInVersion OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, targetIp OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, url OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, correlationId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, implementedByPartialFunction OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, userId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, developerEmail OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, date OBPv600UpdateRateLimitsRequestPropertiesFromDate, consumerId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, operationId OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, verb OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, appName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, sourceIp OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, userName OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties {
	this := OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties{}
	this.Duration = duration
	this.ResponseBody = responseBody
	this.ImplementedInVersion = implementedInVersion
	this.TargetIp = targetIp
	this.Url = url
	this.CorrelationId = correlationId
	this.ImplementedByPartialFunction = implementedByPartialFunction
	this.UserId = userId
	this.DeveloperEmail = developerEmail
	this.Date = date
	this.ConsumerId = consumerId
	this.OperationId = operationId
	this.Verb = verb
	this.AppName = appName
	this.SourceIp = sourceIp
	this.UserName = userName
	return &this
}

// NewOBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesWithDefaults instantiates a new OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesWithDefaults() *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties {
	this := OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties{}
	return &this
}

// GetDuration returns the Duration field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDuration() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDurationOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetDuration(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Duration = v
}

// GetResponseBody returns the ResponseBody field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetResponseBody() OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody {
	if o == nil {
		var ret OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody
		return ret
	}

	return o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetResponseBodyOk() (*OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseBody, true
}

// SetResponseBody sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetResponseBody(v OBPv600GetMetrics200ResponsePropertiesMetricsItemsPropertiesResponseBody) {
	o.ResponseBody = v
}

// GetImplementedInVersion returns the ImplementedInVersion field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetImplementedInVersion() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ImplementedInVersion
}

// GetImplementedInVersionOk returns a tuple with the ImplementedInVersion field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetImplementedInVersionOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImplementedInVersion, true
}

// SetImplementedInVersion sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetImplementedInVersion(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ImplementedInVersion = v
}

// GetTargetIp returns the TargetIp field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetTargetIp() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.TargetIp
}

// GetTargetIpOk returns a tuple with the TargetIp field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetTargetIpOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetIp, true
}

// SetTargetIp sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetTargetIp(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.TargetIp = v
}

// GetUrl returns the Url field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUrl() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUrlOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetUrl(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Url = v
}

// GetCorrelationId returns the CorrelationId field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetCorrelationId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetCorrelationIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrelationId, true
}

// SetCorrelationId sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetCorrelationId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.CorrelationId = v
}

// GetImplementedByPartialFunction returns the ImplementedByPartialFunction field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetImplementedByPartialFunction() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ImplementedByPartialFunction
}

// GetImplementedByPartialFunctionOk returns a tuple with the ImplementedByPartialFunction field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetImplementedByPartialFunctionOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImplementedByPartialFunction, true
}

// SetImplementedByPartialFunction sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetImplementedByPartialFunction(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ImplementedByPartialFunction = v
}

// GetUserId returns the UserId field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUserId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUserIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetUserId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.UserId = v
}

// GetDeveloperEmail returns the DeveloperEmail field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDeveloperEmail() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.DeveloperEmail
}

// GetDeveloperEmailOk returns a tuple with the DeveloperEmail field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDeveloperEmailOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeveloperEmail, true
}

// SetDeveloperEmail sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetDeveloperEmail(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.DeveloperEmail = v
}

// GetDate returns the Date field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDate() OBPv600UpdateRateLimitsRequestPropertiesFromDate {
	if o == nil {
		var ret OBPv600UpdateRateLimitsRequestPropertiesFromDate
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetDateOk() (*OBPv600UpdateRateLimitsRequestPropertiesFromDate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetDate(v OBPv600UpdateRateLimitsRequestPropertiesFromDate) {
	o.Date = v
}

// GetConsumerId returns the ConsumerId field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetConsumerId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.ConsumerId
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetConsumerIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerId, true
}

// SetConsumerId sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetConsumerId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.ConsumerId = v
}

// GetOperationId returns the OperationId field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetOperationId() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetOperationIdOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetOperationId(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.OperationId = v
}

// GetVerb returns the Verb field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetVerb() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.Verb
}

// GetVerbOk returns a tuple with the Verb field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetVerbOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verb, true
}

// SetVerb sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetVerb(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.Verb = v
}

// GetAppName returns the AppName field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetAppName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetAppNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppName, true
}

// SetAppName sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetAppName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.AppName = v
}

// GetSourceIp returns the SourceIp field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetSourceIp() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.SourceIp
}

// GetSourceIpOk returns a tuple with the SourceIp field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetSourceIpOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceIp, true
}

// SetSourceIp sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetSourceIp(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.SourceIp = v
}

// GetUserName returns the UserName field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUserName() OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName {
	if o == nil {
		var ret OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) GetUserNameOk() (*OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) SetUserName(v OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName) {
	o.UserName = v
}

func (o OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["response_body"] = o.ResponseBody
	toSerialize["implemented_in_version"] = o.ImplementedInVersion
	toSerialize["target_ip"] = o.TargetIp
	toSerialize["url"] = o.Url
	toSerialize["correlation_id"] = o.CorrelationId
	toSerialize["implemented_by_partial_function"] = o.ImplementedByPartialFunction
	toSerialize["user_id"] = o.UserId
	toSerialize["developer_email"] = o.DeveloperEmail
	toSerialize["date"] = o.Date
	toSerialize["consumer_id"] = o.ConsumerId
	toSerialize["operation_id"] = o.OperationId
	toSerialize["verb"] = o.Verb
	toSerialize["app_name"] = o.AppName
	toSerialize["source_ip"] = o.SourceIp
	toSerialize["user_name"] = o.UserName
	return toSerialize, nil
}

func (o *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"response_body",
		"implemented_in_version",
		"target_ip",
		"url",
		"correlation_id",
		"implemented_by_partial_function",
		"user_id",
		"developer_email",
		"date",
		"consumer_id",
		"operation_id",
		"verb",
		"app_name",
		"source_ip",
		"user_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties := _OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties)

	if err != nil {
		return err
	}

	*o = OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties(varOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties)

	return err
}

type NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties struct {
	value *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties
	isSet bool
}

func (v NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) Get() *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties {
	return v.value
}

func (v *NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) Set(val *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties(val *OBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) *NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties {
	return &NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties{value: val, isSet: true}
}

func (v NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBPv600GetMetrics200ResponsePropertiesMetricsItemsProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


