/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
import com.openbankproject.model.OBPv600GetActiveRateLimitsAtDate200ResponsePropertiesConsideredRateLimitIds;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.openbankproject.ApiClient;
/**
 * OBPv400UpdateAtmLocationCategories200ResponseProperties
 */
@JsonPropertyOrder({
  OBPv400UpdateAtmLocationCategories200ResponseProperties.JSON_PROPERTY_ATM_ID,
  OBPv400UpdateAtmLocationCategories200ResponseProperties.JSON_PROPERTY_LOCATION_CATEGORIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T11:10:23.425327611+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class OBPv400UpdateAtmLocationCategories200ResponseProperties {
  public static final String JSON_PROPERTY_ATM_ID = "atm_id";
  @javax.annotation.Nonnull
  private OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName atmId;

  public static final String JSON_PROPERTY_LOCATION_CATEGORIES = "location_categories";
  @javax.annotation.Nonnull
  private OBPv600GetActiveRateLimitsAtDate200ResponsePropertiesConsideredRateLimitIds locationCategories;

  public OBPv400UpdateAtmLocationCategories200ResponseProperties() { 
  }

  public OBPv400UpdateAtmLocationCategories200ResponseProperties atmId(@javax.annotation.Nonnull OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName atmId) {
    this.atmId = atmId;
    return this;
  }

  /**
   * Get atmId
   * @return atmId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName getAtmId() {
    return atmId;
  }


  @JsonProperty(value = JSON_PROPERTY_ATM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAtmId(@javax.annotation.Nonnull OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName atmId) {
    this.atmId = atmId;
  }


  public OBPv400UpdateAtmLocationCategories200ResponseProperties locationCategories(@javax.annotation.Nonnull OBPv600GetActiveRateLimitsAtDate200ResponsePropertiesConsideredRateLimitIds locationCategories) {
    this.locationCategories = locationCategories;
    return this;
  }

  /**
   * Get locationCategories
   * @return locationCategories
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OBPv600GetActiveRateLimitsAtDate200ResponsePropertiesConsideredRateLimitIds getLocationCategories() {
    return locationCategories;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocationCategories(@javax.annotation.Nonnull OBPv600GetActiveRateLimitsAtDate200ResponsePropertiesConsideredRateLimitIds locationCategories) {
    this.locationCategories = locationCategories;
  }


  /**
   * Return true if this OBPv4_0_0_updateAtmLocationCategories_200_response_properties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OBPv400UpdateAtmLocationCategories200ResponseProperties obPv400UpdateAtmLocationCategories200ResponseProperties = (OBPv400UpdateAtmLocationCategories200ResponseProperties) o;
    return Objects.equals(this.atmId, obPv400UpdateAtmLocationCategories200ResponseProperties.atmId) &&
        Objects.equals(this.locationCategories, obPv400UpdateAtmLocationCategories200ResponseProperties.locationCategories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atmId, locationCategories);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OBPv400UpdateAtmLocationCategories200ResponseProperties {\n");
    sb.append("    atmId: ").append(toIndentedString(atmId)).append("\n");
    sb.append("    locationCategories: ").append(toIndentedString(locationCategories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `atm_id` to the URL query string
    if (getAtmId() != null) {
      joiner.add(getAtmId().toUrlQueryString(prefix + "atm_id" + suffix));
    }

    // add `location_categories` to the URL query string
    if (getLocationCategories() != null) {
      joiner.add(getLocationCategories().toUrlQueryString(prefix + "location_categories" + suffix));
    }

    return joiner.toString();
  }
}

