//
// OBPv310CreateConsentEmailRequestProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OBPv310CreateConsentEmailRequestProperties: Sendable, Codable, Hashable {

    public var timeToLive: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
    public var email: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
    public var everything: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
    public var consumerId: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
    public var validFrom: OBPv600UpdateRateLimitsRequestPropertiesFromDate
    public var views: OBPv510GetApiTags200ResponsePropertiesAccounts
    public var entitlements: OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements

    public init(timeToLive: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, email: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, everything: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, consumerId: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName, validFrom: OBPv600UpdateRateLimitsRequestPropertiesFromDate, views: OBPv510GetApiTags200ResponsePropertiesAccounts, entitlements: OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements) {
        self.timeToLive = timeToLive
        self.email = email
        self.everything = everything
        self.consumerId = consumerId
        self.validFrom = validFrom
        self.views = views
        self.entitlements = entitlements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeToLive = "time_to_live"
        case email
        case everything
        case consumerId = "consumer_id"
        case validFrom = "valid_from"
        case views
        case entitlements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeToLive, forKey: .timeToLive)
        try container.encode(email, forKey: .email)
        try container.encode(everything, forKey: .everything)
        try container.encode(consumerId, forKey: .consumerId)
        try container.encode(validFrom, forKey: .validFrom)
        try container.encode(views, forKey: .views)
        try container.encode(entitlements, forKey: .entitlements)
    }
}

