//
// OBPv600GetBanks200ResponsePropertiesBanks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OBPv600GetBanks200ResponsePropertiesBanks: Sendable, Codable, Hashable {

    public var type: String
    public var items: OBPv600GetBank200Response

    public init(type: String, items: OBPv600GetBank200Response) {
        self.type = type
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(items, forKey: .items)
    }
}

