=begin
#Open Bank Project API v6.0.0

#The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

The version of the OpenAPI document: 6.0.0
Contact: contact@tesobe.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module OpenBankProject
  class OBPv510CreateVRPConsentRequest200ResponsePropertiesPayloadPropertiesToAccountProperties < ApiModelBase
    attr_accessor :bank_routing

    attr_accessor :account_routing

    attr_accessor :branch_routing

    attr_accessor :limit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bank_routing' => :'bank_routing',
        :'account_routing' => :'account_routing',
        :'branch_routing' => :'branch_routing',
        :'limit' => :'limit'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bank_routing' => :'OBPv310GetCheckbookOrders200ResponsePropertiesAccountPropertiesAccountRoutingsItems',
        :'account_routing' => :'OBPv310GetCheckbookOrders200ResponsePropertiesAccountPropertiesAccountRoutingsItems',
        :'branch_routing' => :'OBPv310GetCheckbookOrders200ResponsePropertiesAccountPropertiesAccountRoutingsItems',
        :'limit' => :'OBPv510CreateVRPConsentRequest200ResponsePropertiesPayloadPropertiesToAccountPropertiesLimit'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenBankProject::OBPv510CreateVRPConsentRequest200ResponsePropertiesPayloadPropertiesToAccountProperties` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenBankProject::OBPv510CreateVRPConsentRequest200ResponsePropertiesPayloadPropertiesToAccountProperties`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bank_routing')
        self.bank_routing = attributes[:'bank_routing']
      else
        self.bank_routing = nil
      end

      if attributes.key?(:'account_routing')
        self.account_routing = attributes[:'account_routing']
      else
        self.account_routing = nil
      end

      if attributes.key?(:'branch_routing')
        self.branch_routing = attributes[:'branch_routing']
      else
        self.branch_routing = nil
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      else
        self.limit = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @bank_routing.nil?
        invalid_properties.push('invalid value for "bank_routing", bank_routing cannot be nil.')
      end

      if @account_routing.nil?
        invalid_properties.push('invalid value for "account_routing", account_routing cannot be nil.')
      end

      if @branch_routing.nil?
        invalid_properties.push('invalid value for "branch_routing", branch_routing cannot be nil.')
      end

      if @limit.nil?
        invalid_properties.push('invalid value for "limit", limit cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @bank_routing.nil?
      return false if @account_routing.nil?
      return false if @branch_routing.nil?
      return false if @limit.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] bank_routing Value to be assigned
    def bank_routing=(bank_routing)
      if bank_routing.nil?
        fail ArgumentError, 'bank_routing cannot be nil'
      end

      @bank_routing = bank_routing
    end

    # Custom attribute writer method with validation
    # @param [Object] account_routing Value to be assigned
    def account_routing=(account_routing)
      if account_routing.nil?
        fail ArgumentError, 'account_routing cannot be nil'
      end

      @account_routing = account_routing
    end

    # Custom attribute writer method with validation
    # @param [Object] branch_routing Value to be assigned
    def branch_routing=(branch_routing)
      if branch_routing.nil?
        fail ArgumentError, 'branch_routing cannot be nil'
      end

      @branch_routing = branch_routing
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      @limit = limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bank_routing == o.bank_routing &&
          account_routing == o.account_routing &&
          branch_routing == o.branch_routing &&
          limit == o.limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bank_routing, account_routing, branch_routing, limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
