// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// OBPv121GetCounterpartyPublicAlias200ResponseProperties
    /// </summary>
    public partial class OBPv121GetCounterpartyPublicAlias200ResponseProperties : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OBPv121GetCounterpartyPublicAlias200ResponseProperties" /> class.
        /// </summary>
        /// <param name="alias">alias</param>
        [JsonConstructor]
        public OBPv121GetCounterpartyPublicAlias200ResponseProperties(OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName alias)
        {
            Alias = alias;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [JsonPropertyName("alias")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Alias { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OBPv121GetCounterpartyPublicAlias200ResponseProperties {\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OBPv121GetCounterpartyPublicAlias200ResponseProperties" />
    /// </summary>
    public class OBPv121GetCounterpartyPublicAlias200ResponsePropertiesJsonConverter : JsonConverter<OBPv121GetCounterpartyPublicAlias200ResponseProperties>
    {
        /// <summary>
        /// Deserializes json to <see cref="OBPv121GetCounterpartyPublicAlias200ResponseProperties" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OBPv121GetCounterpartyPublicAlias200ResponseProperties Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> alias = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "alias":
                            alias = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!alias.IsSet)
                throw new ArgumentException("Property is required for class OBPv121GetCounterpartyPublicAlias200ResponseProperties.", nameof(alias));

            if (alias.IsSet && alias.Value == null)
                throw new ArgumentNullException(nameof(alias), "Property is not nullable for class OBPv121GetCounterpartyPublicAlias200ResponseProperties.");

            return new OBPv121GetCounterpartyPublicAlias200ResponseProperties(alias.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OBPv121GetCounterpartyPublicAlias200ResponseProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv121GetCounterpartyPublicAlias200ResponseProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OBPv121GetCounterpartyPublicAlias200ResponseProperties oBPv121GetCounterpartyPublicAlias200ResponseProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oBPv121GetCounterpartyPublicAlias200ResponseProperties, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OBPv121GetCounterpartyPublicAlias200ResponseProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv121GetCounterpartyPublicAlias200ResponseProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OBPv121GetCounterpartyPublicAlias200ResponseProperties oBPv121GetCounterpartyPublicAlias200ResponseProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oBPv121GetCounterpartyPublicAlias200ResponseProperties.Alias == null)
                throw new ArgumentNullException(nameof(oBPv121GetCounterpartyPublicAlias200ResponseProperties.Alias), "Property is required for class OBPv121GetCounterpartyPublicAlias200ResponseProperties.");

            writer.WritePropertyName("alias");
            JsonSerializer.Serialize(writer, oBPv121GetCounterpartyPublicAlias200ResponseProperties.Alias, jsonSerializerOptions);
        }
    }
}
