// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties
    /// </summary>
    public partial class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties" /> class.
        /// </summary>
        /// <param name="duration">duration</param>
        /// <param name="implementedInVersion">implementedInVersion</param>
        /// <param name="url">url</param>
        /// <param name="correlationId">correlationId</param>
        /// <param name="implementedByPartialFunction">implementedByPartialFunction</param>
        /// <param name="userId">userId</param>
        /// <param name="developerEmail">developerEmail</param>
        /// <param name="date">date</param>
        /// <param name="consumerId">consumerId</param>
        /// <param name="verb">verb</param>
        /// <param name="appName">appName</param>
        /// <param name="userName">userName</param>
        [JsonConstructor]
        public OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties(OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName duration, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName implementedInVersion, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName url, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName correlationId, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName implementedByPartialFunction, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName userId, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName developerEmail, OBPv600UpdateRateLimitsRequestPropertiesFromDate date, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName consumerId, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName verb, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName appName, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName userName)
        {
            Duration = duration;
            ImplementedInVersion = implementedInVersion;
            Url = url;
            CorrelationId = correlationId;
            ImplementedByPartialFunction = implementedByPartialFunction;
            UserId = userId;
            DeveloperEmail = developerEmail;
            Date = date;
            ConsumerId = consumerId;
            Verb = verb;
            AppName = appName;
            UserName = userName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [JsonPropertyName("duration")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Duration { get; set; }

        /// <summary>
        /// Gets or Sets ImplementedInVersion
        /// </summary>
        [JsonPropertyName("implemented_in_version")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ImplementedInVersion { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Url { get; set; }

        /// <summary>
        /// Gets or Sets CorrelationId
        /// </summary>
        [JsonPropertyName("correlation_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName CorrelationId { get; set; }

        /// <summary>
        /// Gets or Sets ImplementedByPartialFunction
        /// </summary>
        [JsonPropertyName("implemented_by_partial_function")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ImplementedByPartialFunction { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("user_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName UserId { get; set; }

        /// <summary>
        /// Gets or Sets DeveloperEmail
        /// </summary>
        [JsonPropertyName("developer_email")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName DeveloperEmail { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public OBPv600UpdateRateLimitsRequestPropertiesFromDate Date { get; set; }

        /// <summary>
        /// Gets or Sets ConsumerId
        /// </summary>
        [JsonPropertyName("consumer_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ConsumerId { get; set; }

        /// <summary>
        /// Gets or Sets Verb
        /// </summary>
        [JsonPropertyName("verb")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Verb { get; set; }

        /// <summary>
        /// Gets or Sets AppName
        /// </summary>
        [JsonPropertyName("app_name")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName AppName { get; set; }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [JsonPropertyName("user_name")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName UserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties {\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  ImplementedInVersion: ").Append(ImplementedInVersion).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  ImplementedByPartialFunction: ").Append(ImplementedByPartialFunction).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  DeveloperEmail: ").Append(DeveloperEmail).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  ConsumerId: ").Append(ConsumerId).Append("\n");
            sb.Append("  Verb: ").Append(Verb).Append("\n");
            sb.Append("  AppName: ").Append(AppName).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties" />
    /// </summary>
    public class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsPropertiesJsonConverter : JsonConverter<OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties>
    {
        /// <summary>
        /// Deserializes json to <see cref="OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> duration = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> implementedInVersion = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> url = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> correlationId = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> implementedByPartialFunction = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> userId = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> developerEmail = default;
            Option<OBPv600UpdateRateLimitsRequestPropertiesFromDate?> date = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> consumerId = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> verb = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> appName = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> userName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "duration":
                            duration = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "implemented_in_version":
                            implementedInVersion = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "url":
                            url = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "correlation_id":
                            correlationId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "implemented_by_partial_function":
                            implementedByPartialFunction = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "user_id":
                            userId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "developer_email":
                            developerEmail = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "date":
                            date = new Option<OBPv600UpdateRateLimitsRequestPropertiesFromDate?>(JsonSerializer.Deserialize<OBPv600UpdateRateLimitsRequestPropertiesFromDate>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "consumer_id":
                            consumerId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "verb":
                            verb = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "app_name":
                            appName = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "user_name":
                            userName = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!duration.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(duration));

            if (!implementedInVersion.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(implementedInVersion));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(url));

            if (!correlationId.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(correlationId));

            if (!implementedByPartialFunction.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(implementedByPartialFunction));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(userId));

            if (!developerEmail.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(developerEmail));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(date));

            if (!consumerId.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(consumerId));

            if (!verb.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(verb));

            if (!appName.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(appName));

            if (!userName.IsSet)
                throw new ArgumentException("Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.", nameof(userName));

            if (duration.IsSet && duration.Value == null)
                throw new ArgumentNullException(nameof(duration), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (implementedInVersion.IsSet && implementedInVersion.Value == null)
                throw new ArgumentNullException(nameof(implementedInVersion), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (correlationId.IsSet && correlationId.Value == null)
                throw new ArgumentNullException(nameof(correlationId), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (implementedByPartialFunction.IsSet && implementedByPartialFunction.Value == null)
                throw new ArgumentNullException(nameof(implementedByPartialFunction), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (developerEmail.IsSet && developerEmail.Value == null)
                throw new ArgumentNullException(nameof(developerEmail), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (consumerId.IsSet && consumerId.Value == null)
                throw new ArgumentNullException(nameof(consumerId), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (verb.IsSet && verb.Value == null)
                throw new ArgumentNullException(nameof(verb), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (appName.IsSet && appName.Value == null)
                throw new ArgumentNullException(nameof(appName), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            return new OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties(duration.Value!, implementedInVersion.Value!, url.Value!, correlationId.Value!, implementedByPartialFunction.Value!, userId.Value!, developerEmail.Value!, date.Value!, consumerId.Value!, verb.Value!, appName.Value!, userName.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Duration == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Duration), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedInVersion == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedInVersion), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Url == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Url), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.CorrelationId == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.CorrelationId), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedByPartialFunction == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedByPartialFunction), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserId == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserId), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.DeveloperEmail == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.DeveloperEmail), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Date == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Date), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ConsumerId == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ConsumerId), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Verb == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Verb), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.AppName == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.AppName), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            if (oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserName == null)
                throw new ArgumentNullException(nameof(oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserName), "Property is required for class OBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.");

            writer.WritePropertyName("duration");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Duration, jsonSerializerOptions);
            writer.WritePropertyName("implemented_in_version");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedInVersion, jsonSerializerOptions);
            writer.WritePropertyName("url");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Url, jsonSerializerOptions);
            writer.WritePropertyName("correlation_id");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.CorrelationId, jsonSerializerOptions);
            writer.WritePropertyName("implemented_by_partial_function");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ImplementedByPartialFunction, jsonSerializerOptions);
            writer.WritePropertyName("user_id");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserId, jsonSerializerOptions);
            writer.WritePropertyName("developer_email");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.DeveloperEmail, jsonSerializerOptions);
            writer.WritePropertyName("date");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Date, jsonSerializerOptions);
            writer.WritePropertyName("consumer_id");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.ConsumerId, jsonSerializerOptions);
            writer.WritePropertyName("verb");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.Verb, jsonSerializerOptions);
            writer.WritePropertyName("app_name");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.AppName, jsonSerializerOptions);
            writer.WritePropertyName("user_name");
            JsonSerializer.Serialize(writer, oBPv500GetMetricsAtBank200ResponsePropertiesMetricsItemsProperties.UserName, jsonSerializerOptions);
        }
    }
}
