// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// OBPv510GetConsentByConsentId200ResponseProperties
    /// </summary>
    public partial class OBPv510GetConsentByConsentId200ResponseProperties : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OBPv510GetConsentByConsentId200ResponseProperties" /> class.
        /// </summary>
        /// <param name="scopes">scopes</param>
        /// <param name="jwt">jwt</param>
        /// <param name="consentRequestId">consentRequestId</param>
        /// <param name="status">status</param>
        /// <param name="consumerId">consumerId</param>
        /// <param name="consentId">consentId</param>
        [JsonConstructor]
        public OBPv510GetConsentByConsentId200ResponseProperties(OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements scopes, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName jwt, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName consentRequestId, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName status, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName consumerId, OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName consentId)
        {
            Scopes = scopes;
            Jwt = jwt;
            ConsentRequestId = consentRequestId;
            Status = status;
            ConsumerId = consumerId;
            ConsentId = consentId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Scopes
        /// </summary>
        [JsonPropertyName("scopes")]
        public OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements Scopes { get; set; }

        /// <summary>
        /// Gets or Sets Jwt
        /// </summary>
        [JsonPropertyName("jwt")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Jwt { get; set; }

        /// <summary>
        /// Gets or Sets ConsentRequestId
        /// </summary>
        [JsonPropertyName("consent_request_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ConsentRequestId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName Status { get; set; }

        /// <summary>
        /// Gets or Sets ConsumerId
        /// </summary>
        [JsonPropertyName("consumer_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ConsumerId { get; set; }

        /// <summary>
        /// Gets or Sets ConsentId
        /// </summary>
        [JsonPropertyName("consent_id")]
        public OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName ConsentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OBPv510GetConsentByConsentId200ResponseProperties {\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  Jwt: ").Append(Jwt).Append("\n");
            sb.Append("  ConsentRequestId: ").Append(ConsentRequestId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ConsumerId: ").Append(ConsumerId).Append("\n");
            sb.Append("  ConsentId: ").Append(ConsentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OBPv510GetConsentByConsentId200ResponseProperties" />
    /// </summary>
    public class OBPv510GetConsentByConsentId200ResponsePropertiesJsonConverter : JsonConverter<OBPv510GetConsentByConsentId200ResponseProperties>
    {
        /// <summary>
        /// Deserializes json to <see cref="OBPv510GetConsentByConsentId200ResponseProperties" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OBPv510GetConsentByConsentId200ResponseProperties Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements?> scopes = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> jwt = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> consentRequestId = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> status = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> consumerId = default;
            Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?> consentId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "scopes":
                            scopes = new Option<OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements?>(JsonSerializer.Deserialize<OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesEntitlements>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "jwt":
                            jwt = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "consent_request_id":
                            consentRequestId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            status = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "consumer_id":
                            consumerId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "consent_id":
                            consentId = new Option<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName?>(JsonSerializer.Deserialize<OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!scopes.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(scopes));

            if (!jwt.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(jwt));

            if (!consentRequestId.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(consentRequestId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(status));

            if (!consumerId.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(consumerId));

            if (!consentId.IsSet)
                throw new ArgumentException("Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.", nameof(consentId));

            if (scopes.IsSet && scopes.Value == null)
                throw new ArgumentNullException(nameof(scopes), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (jwt.IsSet && jwt.Value == null)
                throw new ArgumentNullException(nameof(jwt), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (consentRequestId.IsSet && consentRequestId.Value == null)
                throw new ArgumentNullException(nameof(consentRequestId), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (consumerId.IsSet && consumerId.Value == null)
                throw new ArgumentNullException(nameof(consumerId), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (consentId.IsSet && consentId.Value == null)
                throw new ArgumentNullException(nameof(consentId), "Property is not nullable for class OBPv510GetConsentByConsentId200ResponseProperties.");

            return new OBPv510GetConsentByConsentId200ResponseProperties(scopes.Value!, jwt.Value!, consentRequestId.Value!, status.Value!, consumerId.Value!, consentId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OBPv510GetConsentByConsentId200ResponseProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv510GetConsentByConsentId200ResponseProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OBPv510GetConsentByConsentId200ResponseProperties oBPv510GetConsentByConsentId200ResponseProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oBPv510GetConsentByConsentId200ResponseProperties, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OBPv510GetConsentByConsentId200ResponseProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oBPv510GetConsentByConsentId200ResponseProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OBPv510GetConsentByConsentId200ResponseProperties oBPv510GetConsentByConsentId200ResponseProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oBPv510GetConsentByConsentId200ResponseProperties.Scopes == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.Scopes), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (oBPv510GetConsentByConsentId200ResponseProperties.Jwt == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.Jwt), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (oBPv510GetConsentByConsentId200ResponseProperties.ConsentRequestId == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.ConsentRequestId), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (oBPv510GetConsentByConsentId200ResponseProperties.Status == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.Status), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (oBPv510GetConsentByConsentId200ResponseProperties.ConsumerId == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.ConsumerId), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            if (oBPv510GetConsentByConsentId200ResponseProperties.ConsentId == null)
                throw new ArgumentNullException(nameof(oBPv510GetConsentByConsentId200ResponseProperties.ConsentId), "Property is required for class OBPv510GetConsentByConsentId200ResponseProperties.");

            writer.WritePropertyName("scopes");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.Scopes, jsonSerializerOptions);
            writer.WritePropertyName("jwt");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.Jwt, jsonSerializerOptions);
            writer.WritePropertyName("consent_request_id");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.ConsentRequestId, jsonSerializerOptions);
            writer.WritePropertyName("status");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.Status, jsonSerializerOptions);
            writer.WritePropertyName("consumer_id");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.ConsumerId, jsonSerializerOptions);
            writer.WritePropertyName("consent_id");
            JsonSerializer.Serialize(writer, oBPv510GetConsentByConsentId200ResponseProperties.ConsentId, jsonSerializerOptions);
        }
    }
}
