# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv500_get_customer_account_links_by_customer_id200_response_properties_links import OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks

class TestOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks(unittest.TestCase):
    """OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks:
        """Test OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks`
        """
        model = OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks()
        if include_optional:
            return OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks(
                type = '',
                items = obp_python.models.obpv5_0_0_get_customer_account_links_by_customer_id_200_response_properties_links_items.OBPv5_0_0_getCustomerAccountLinksByCustomerId_200_response_properties_links_items(
                    type = '', 
                    properties = obp_python.models.obpv5_0_0_get_customer_account_links_by_customer_id_200_response_properties_links_items_properties.OBPv5_0_0_getCustomerAccountLinksByCustomerId_200_response_properties_links_items_properties(
                        customer_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        customer_account_link_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        bank_id = , 
                        account_id = , 
                        relationship_type = , ), )
            )
        else:
            return OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks(
                type = '',
                items = obp_python.models.obpv5_0_0_get_customer_account_links_by_customer_id_200_response_properties_links_items.OBPv5_0_0_getCustomerAccountLinksByCustomerId_200_response_properties_links_items(
                    type = '', 
                    properties = obp_python.models.obpv5_0_0_get_customer_account_links_by_customer_id_200_response_properties_links_items_properties.OBPv5_0_0_getCustomerAccountLinksByCustomerId_200_response_properties_links_items_properties(
                        customer_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        customer_account_link_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        bank_id = , 
                        account_id = , 
                        relationship_type = , ), ),
        )
        """

    def testOBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks(self):
        """Test OBPv500GetCustomerAccountLinksByCustomerId200ResponsePropertiesLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
