# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv310_get_cards_for_bank200_response_properties_cards_items_properties_replacement_properties import OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties

class TestOBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties(unittest.TestCase):
    """OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties:
        """Test OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties`
        """
        model = OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties()
        if include_optional:
            return OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties(
                reason_requested = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                    type = '', ),
                requested_date = obp_python.models.obpv6_0_0_update_rate_limits_request_properties_from_date.OBPv6_0_0_updateRateLimits_request_properties_from_date(
                    type = '', 
                    format = '', )
            )
        else:
            return OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties(
                reason_requested = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                    type = '', ),
                requested_date = obp_python.models.obpv6_0_0_update_rate_limits_request_properties_from_date.OBPv6_0_0_updateRateLimits_request_properties_from_date(
                    type = '', 
                    format = '', ),
        )
        """

    def testOBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties(self):
        """Test OBPv310GetCardsForBank200ResponsePropertiesCardsItemsPropertiesReplacementProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
