# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv400_get_counterparties_for_any_account200_response_properties_counterparties_items import OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems

class TestOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems(unittest.TestCase):
    """OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems:
        """Test OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems`
        """
        model = OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems()
        if include_optional:
            return OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems(
                type = '',
                properties = obp_python.models.obpv4_0_0_get_counterparties_for_any_account_200_response_properties_counterparties_items_properties.OBPv4_0_0_getCounterpartiesForAnyAccount_200_response_properties_counterparties_items_properties(
                    other_account_routing_address = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    other_account_routing_scheme = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    created_by_user_id = , 
                    name = , 
                    other_account_secondary_routing_address = , 
                    is_beneficiary = , 
                    description = , 
                    other_branch_routing_address = , 
                    bespoke = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke(
                        type = '', 
                        items = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke_items.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke_items(
                            type = '', 
                            properties = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke_items_properties.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke_items_properties(
                                value = , 
                                key = , ), ), ), 
                    other_bank_routing_scheme = , 
                    other_branch_routing_scheme = , 
                    this_account_id = , 
                    this_view_id = , 
                    currency = , 
                    other_bank_routing_address = , 
                    this_bank_id = , 
                    counterparty_id = , 
                    other_account_secondary_routing_scheme = , )
            )
        else:
            return OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems(
                type = '',
                properties = obp_python.models.obpv4_0_0_get_counterparties_for_any_account_200_response_properties_counterparties_items_properties.OBPv4_0_0_getCounterpartiesForAnyAccount_200_response_properties_counterparties_items_properties(
                    other_account_routing_address = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    other_account_routing_scheme = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    created_by_user_id = , 
                    name = , 
                    other_account_secondary_routing_address = , 
                    is_beneficiary = , 
                    description = , 
                    other_branch_routing_address = , 
                    bespoke = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke(
                        type = '', 
                        items = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke_items.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke_items(
                            type = '', 
                            properties = obp_python.models.obpv4_0_0_get_explicit_counterparty_by_id_200_response_properties_bespoke_items_properties.OBPv4_0_0_getExplicitCounterpartyById_200_response_properties_bespoke_items_properties(
                                value = , 
                                key = , ), ), ), 
                    other_bank_routing_scheme = , 
                    other_branch_routing_scheme = , 
                    this_account_id = , 
                    this_view_id = , 
                    currency = , 
                    other_bank_routing_address = , 
                    this_bank_id = , 
                    counterparty_id = , 
                    other_account_secondary_routing_scheme = , ),
        )
        """

    def testOBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems(self):
        """Test OBPv400GetCounterpartiesForAnyAccount200ResponsePropertiesCounterpartiesItems"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
