# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv400_get_bank_attributes200_response_properties import OBPv400GetBankAttributes200ResponseProperties

class TestOBPv400GetBankAttributes200ResponseProperties(unittest.TestCase):
    """OBPv400GetBankAttributes200ResponseProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv400GetBankAttributes200ResponseProperties:
        """Test OBPv400GetBankAttributes200ResponseProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv400GetBankAttributes200ResponseProperties`
        """
        model = OBPv400GetBankAttributes200ResponseProperties()
        if include_optional:
            return OBPv400GetBankAttributes200ResponseProperties(
                bank_attributes = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes(
                    type = '', 
                    items = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes_items.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes_items(
                        type = '', 
                        properties = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes_items_properties.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes_items_properties(
                            name = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            is_active = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            bank_attribute_id = , 
                            bank_id = , 
                            type = , 
                            value = , ), ), )
            )
        else:
            return OBPv400GetBankAttributes200ResponseProperties(
                bank_attributes = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes(
                    type = '', 
                    items = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes_items.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes_items(
                        type = '', 
                        properties = obp_python.models.obpv4_0_0_get_bank_attributes_200_response_properties_bank_attributes_items_properties.OBPv4_0_0_getBankAttributes_200_response_properties_bank_attributes_items_properties(
                            name = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            is_active = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            bank_attribute_id = , 
                            bank_id = , 
                            type = , 
                            value = , ), ), ),
        )
        """

    def testOBPv400GetBankAttributes200ResponseProperties(self):
        """Test OBPv400GetBankAttributes200ResponseProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
