# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv600_get_cache_namespaces200_response_properties_namespaces import OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces

class TestOBPv600GetCacheNamespaces200ResponsePropertiesNamespaces(unittest.TestCase):
    """OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces:
        """Test OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces`
        """
        model = OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces()
        if include_optional:
            return OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces(
                type = '',
                items = obp_python.models.obpv6_0_0_get_cache_namespaces_200_response_properties_namespaces_items.OBPv6_0_0_getCacheNamespaces_200_response_properties_namespaces_items(
                    type = '', 
                    properties = obp_python.models.obpv6_0_0_get_cache_namespaces_200_response_properties_namespaces_items_properties.OBPv6_0_0_getCacheNamespaces_200_response_properties_namespaces_items_properties(
                        ttl_seconds = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        example_key = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        description = , 
                        prefix = , 
                        category = , 
                        key_count = , ), )
            )
        else:
            return OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces(
                type = '',
                items = obp_python.models.obpv6_0_0_get_cache_namespaces_200_response_properties_namespaces_items.OBPv6_0_0_getCacheNamespaces_200_response_properties_namespaces_items(
                    type = '', 
                    properties = obp_python.models.obpv6_0_0_get_cache_namespaces_200_response_properties_namespaces_items_properties.OBPv6_0_0_getCacheNamespaces_200_response_properties_namespaces_items_properties(
                        ttl_seconds = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        example_key = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                            type = '', ), 
                        description = , 
                        prefix = , 
                        category = , 
                        key_count = , ), ),
        )
        """

    def testOBPv600GetCacheNamespaces200ResponsePropertiesNamespaces(self):
        """Test OBPv600GetCacheNamespaces200ResponsePropertiesNamespaces"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
