# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv600_update_system_dynamic_entity200_response import OBPv600UpdateSystemDynamicEntity200Response

class TestOBPv600UpdateSystemDynamicEntity200Response(unittest.TestCase):
    """OBPv600UpdateSystemDynamicEntity200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv600UpdateSystemDynamicEntity200Response:
        """Test OBPv600UpdateSystemDynamicEntity200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv600UpdateSystemDynamicEntity200Response`
        """
        model = OBPv600UpdateSystemDynamicEntity200Response()
        if include_optional:
            return OBPv600UpdateSystemDynamicEntity200Response(
                type = '',
                properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_200_response_properties.OBPv6_0_0_updateSystemDynamicEntity_200_response_properties(
                    personal_requires_role = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    user_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    entity_name = , 
                    dynamic_entity_id = , 
                    schema = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema(
                        type = '', 
                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties(
                            description = , 
                            required = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields_.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields_(
                                type = '', 
                                items = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields__items.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields__items(
                                    type = '', 
                                    properties = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields__items_properties.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields__items_properties(
                                        s = , ), ), ), 
                            properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties(
                                type = '', 
                                properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties(
                                    theme = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme_properties(
                                            description = , 
                                            min_length = , 
                                            type = , 
                                            example = , 
                                            max_length = , ), ), 
                                    language = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme_properties(
                                            description = , 
                                            min_length = , 
                                            type = , 
                                            example = , 
                                            max_length = , ), ), 
                                    notifications_enabled = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_notifications_enabled.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_notifications_enabled(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_notifications_enabled_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_notifications_enabled_properties(
                                            type = , 
                                            example = , 
                                            description = , ), ), ), ), ), ), 
                    has_public_access = , 
                    has_community_access = , 
                    has_personal_entity = , )
            )
        else:
            return OBPv600UpdateSystemDynamicEntity200Response(
                type = '',
                properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_200_response_properties.OBPv6_0_0_updateSystemDynamicEntity_200_response_properties(
                    personal_requires_role = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    user_id = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    entity_name = , 
                    dynamic_entity_id = , 
                    schema = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema(
                        type = '', 
                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties(
                            description = , 
                            required = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields_.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields_(
                                type = '', 
                                items = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields__items.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields__items(
                                    type = '', 
                                    properties = obp_python.models.obpv4_0_0_get_bank_level_dynamic_resource_doc_200_response_properties_success_response_body_properties__optional_fields__items_properties.OBPv4_0_0_getBankLevelDynamicResourceDoc_200_response_properties_success_response_body_properties__optional_fields__items_properties(
                                        s = , ), ), ), 
                            properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties(
                                type = '', 
                                properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties(
                                    theme = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme_properties(
                                            description = , 
                                            min_length = , 
                                            type = , 
                                            example = , 
                                            max_length = , ), ), 
                                    language = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_theme_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_theme_properties(
                                            description = , 
                                            min_length = , 
                                            type = , 
                                            example = , 
                                            max_length = , ), ), 
                                    notifications_enabled = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_notifications_enabled.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_notifications_enabled(
                                        type = '', 
                                        properties = obp_python.models.obpv6_0_0_update_system_dynamic_entity_request_properties_schema_properties_properties_properties_notifications_enabled_properties.OBPv6_0_0_updateSystemDynamicEntity_request_properties_schema_properties_properties_properties_notifications_enabled_properties(
                                            type = , 
                                            example = , 
                                            description = , ), ), ), ), ), ), 
                    has_public_access = , 
                    has_community_access = , 
                    has_personal_entity = , ),
        )
        """

    def testOBPv600UpdateSystemDynamicEntity200Response(self):
        """Test OBPv600UpdateSystemDynamicEntity200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
