# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv121_update_counterparty_physical_location_request import OBPv121UpdateCounterpartyPhysicalLocationRequest

class TestOBPv121UpdateCounterpartyPhysicalLocationRequest(unittest.TestCase):
    """OBPv121UpdateCounterpartyPhysicalLocationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv121UpdateCounterpartyPhysicalLocationRequest:
        """Test OBPv121UpdateCounterpartyPhysicalLocationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv121UpdateCounterpartyPhysicalLocationRequest`
        """
        model = OBPv121UpdateCounterpartyPhysicalLocationRequest()
        if include_optional:
            return OBPv121UpdateCounterpartyPhysicalLocationRequest(
                type = '',
                properties = obp_python.models.obpv1_2_1_update_counterparty_physical_location_request_properties.OBPv1_2_1_updateCounterpartyPhysicalLocation_request_properties(
                    physical_location = obp_python.models.obpv3_0_0_get_branches_200_response_properties_branches_items_properties_location.OBPv3_0_0_getBranches_200_response_properties_branches_items_properties_location(
                        type = '', 
                        properties = obp_python.models.obpv3_0_0_get_branches_200_response_properties_branches_items_properties_location_properties.OBPv3_0_0_getBranches_200_response_properties_branches_items_properties_location_properties(
                            latitude = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            longitude = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), ), ), )
            )
        else:
            return OBPv121UpdateCounterpartyPhysicalLocationRequest(
                type = '',
                properties = obp_python.models.obpv1_2_1_update_counterparty_physical_location_request_properties.OBPv1_2_1_updateCounterpartyPhysicalLocation_request_properties(
                    physical_location = obp_python.models.obpv3_0_0_get_branches_200_response_properties_branches_items_properties_location.OBPv3_0_0_getBranches_200_response_properties_branches_items_properties_location(
                        type = '', 
                        properties = obp_python.models.obpv3_0_0_get_branches_200_response_properties_branches_items_properties_location_properties.OBPv3_0_0_getBranches_200_response_properties_branches_items_properties_location_properties(
                            latitude = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), 
                            longitude = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                                type = '', ), ), ), ),
        )
        """

    def testOBPv121UpdateCounterpartyPhysicalLocationRequest(self):
        """Test OBPv121UpdateCounterpartyPhysicalLocationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
