# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.obpv600_create_account_access_request_request import OBPv600CreateAccountAccessRequestRequest

class TestOBPv600CreateAccountAccessRequestRequest(unittest.TestCase):
    """OBPv600CreateAccountAccessRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OBPv600CreateAccountAccessRequestRequest:
        """Test OBPv600CreateAccountAccessRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OBPv600CreateAccountAccessRequestRequest`
        """
        model = OBPv600CreateAccountAccessRequestRequest()
        if include_optional:
            return OBPv600CreateAccountAccessRequestRequest(
                type = '',
                properties = obp_python.models.obpv6_0_0_create_account_access_request_request_properties.OBPv6_0_0_createAccountAccessRequest_request_properties(
                    is_system_view = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    business_justification = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    view_id = , 
                    target_user_id = , )
            )
        else:
            return OBPv600CreateAccountAccessRequestRequest(
                type = '',
                properties = obp_python.models.obpv6_0_0_create_account_access_request_request_properties.OBPv6_0_0_createAccountAccessRequest_request_properties(
                    is_system_view = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    business_justification = obp_python.models.obpv4_0_0_update_system_level_endpoint_tag_request_properties_tag_name.OBPv4_0_0_updateSystemLevelEndpointTag_request_properties_tag_name(
                        type = '', ), 
                    view_id = , 
                    target_user_id = , ),
        )
        """

    def testOBPv600CreateAccountAccessRequestRequest(self):
        """Test OBPv600CreateAccountAccessRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
