/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv500GetSystemViewsIds200ResponsePropertiesViews } from './OBPv500GetSystemViewsIds200ResponsePropertiesViews';
import {
    OBPv500GetSystemViewsIds200ResponsePropertiesViewsFromJSON,
    OBPv500GetSystemViewsIds200ResponsePropertiesViewsFromJSONTyped,
    OBPv500GetSystemViewsIds200ResponsePropertiesViewsToJSON,
    OBPv500GetSystemViewsIds200ResponsePropertiesViewsToJSONTyped,
} from './OBPv500GetSystemViewsIds200ResponsePropertiesViews';

/**
 * 
 * @export
 * @interface OBPv500GetSystemViewsIds200ResponseProperties
 */
export interface OBPv500GetSystemViewsIds200ResponseProperties {
    /**
     * 
     * @type {OBPv500GetSystemViewsIds200ResponsePropertiesViews}
     * @memberof OBPv500GetSystemViewsIds200ResponseProperties
     */
    views: OBPv500GetSystemViewsIds200ResponsePropertiesViews;
}

/**
 * Check if a given object implements the OBPv500GetSystemViewsIds200ResponseProperties interface.
 */
export function instanceOfOBPv500GetSystemViewsIds200ResponseProperties(value: object): value is OBPv500GetSystemViewsIds200ResponseProperties {
    if (!('views' in value) || value['views'] === undefined) return false;
    return true;
}

export function OBPv500GetSystemViewsIds200ResponsePropertiesFromJSON(json: any): OBPv500GetSystemViewsIds200ResponseProperties {
    return OBPv500GetSystemViewsIds200ResponsePropertiesFromJSONTyped(json, false);
}

export function OBPv500GetSystemViewsIds200ResponsePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv500GetSystemViewsIds200ResponseProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'views': OBPv500GetSystemViewsIds200ResponsePropertiesViewsFromJSON(json['views']),
    };
}

export function OBPv500GetSystemViewsIds200ResponsePropertiesToJSON(json: any): OBPv500GetSystemViewsIds200ResponseProperties {
    return OBPv500GetSystemViewsIds200ResponsePropertiesToJSONTyped(json, false);
}

export function OBPv500GetSystemViewsIds200ResponsePropertiesToJSONTyped(value?: OBPv500GetSystemViewsIds200ResponseProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'views': OBPv500GetSystemViewsIds200ResponsePropertiesViewsToJSON(value['views']),
    };
}

