/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersions } from './OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersions';
import {
    OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsFromJSON,
    OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsFromJSONTyped,
    OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsToJSON,
    OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsToJSONTyped,
} from './OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersions';

/**
 * 
 * @export
 * @interface OBPv600GetScannedApiVersions200ResponseProperties
 */
export interface OBPv600GetScannedApiVersions200ResponseProperties {
    /**
     * 
     * @type {OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersions}
     * @memberof OBPv600GetScannedApiVersions200ResponseProperties
     */
    scannedApiVersions: OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersions;
}

/**
 * Check if a given object implements the OBPv600GetScannedApiVersions200ResponseProperties interface.
 */
export function instanceOfOBPv600GetScannedApiVersions200ResponseProperties(value: object): value is OBPv600GetScannedApiVersions200ResponseProperties {
    if (!('scannedApiVersions' in value) || value['scannedApiVersions'] === undefined) return false;
    return true;
}

export function OBPv600GetScannedApiVersions200ResponsePropertiesFromJSON(json: any): OBPv600GetScannedApiVersions200ResponseProperties {
    return OBPv600GetScannedApiVersions200ResponsePropertiesFromJSONTyped(json, false);
}

export function OBPv600GetScannedApiVersions200ResponsePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv600GetScannedApiVersions200ResponseProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'scannedApiVersions': OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsFromJSON(json['scanned_api_versions']),
    };
}

export function OBPv600GetScannedApiVersions200ResponsePropertiesToJSON(json: any): OBPv600GetScannedApiVersions200ResponseProperties {
    return OBPv600GetScannedApiVersions200ResponsePropertiesToJSONTyped(json, false);
}

export function OBPv600GetScannedApiVersions200ResponsePropertiesToJSONTyped(value?: OBPv600GetScannedApiVersions200ResponseProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanned_api_versions': OBPv600GetScannedApiVersions200ResponsePropertiesScannedApiVersionsToJSON(value['scannedApiVersions']),
    };
}

