/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsProperties } from './OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsProperties';
import {
    OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesFromJSON,
    OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesFromJSONTyped,
    OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesToJSON,
    OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesToJSONTyped,
} from './OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsProperties';

/**
 * 
 * @export
 * @interface OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems
 */
export interface OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems {
    /**
     * 
     * @type {string}
     * @memberof OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems
     */
    type: string;
    /**
     * 
     * @type {OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsProperties}
     * @memberof OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems
     */
    properties: OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsProperties;
}

/**
 * Check if a given object implements the OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems interface.
 */
export function instanceOfOBPv600GetViewPermissions200ResponsePropertiesPermissionsItems(value: object): value is OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsFromJSON(json: any): OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems {
    return OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsFromJSONTyped(json, false);
}

export function OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'properties': OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesFromJSON(json['properties']),
    };
}

export function OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsToJSON(json: any): OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems {
    return OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsToJSONTyped(json, false);
}

export function OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsToJSONTyped(value?: OBPv600GetViewPermissions200ResponsePropertiesPermissionsItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'properties': OBPv600GetViewPermissions200ResponsePropertiesPermissionsItemsPropertiesToJSON(value['properties']),
    };
}

