/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName } from './OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName';
import {
    OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameFromJSON,
    OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameFromJSONTyped,
    OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameToJSON,
    OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameToJSONTyped,
} from './OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName';
import type { OBPv600UpdateRateLimitsRequestPropertiesFromDate } from './OBPv600UpdateRateLimitsRequestPropertiesFromDate';
import {
    OBPv600UpdateRateLimitsRequestPropertiesFromDateFromJSON,
    OBPv600UpdateRateLimitsRequestPropertiesFromDateFromJSONTyped,
    OBPv600UpdateRateLimitsRequestPropertiesFromDateToJSON,
    OBPv600UpdateRateLimitsRequestPropertiesFromDateToJSONTyped,
} from './OBPv600UpdateRateLimitsRequestPropertiesFromDate';

/**
 * 
 * @export
 * @interface OBPv400CreateDirectDebitRequestProperties
 */
export interface OBPv400CreateDirectDebitRequestProperties {
    /**
     * 
     * @type {OBPv600UpdateRateLimitsRequestPropertiesFromDate}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    dateStarts: OBPv600UpdateRateLimitsRequestPropertiesFromDate;
    /**
     * 
     * @type {OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    customerId: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
    /**
     * 
     * @type {OBPv600UpdateRateLimitsRequestPropertiesFromDate}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    dateSigned: OBPv600UpdateRateLimitsRequestPropertiesFromDate;
    /**
     * 
     * @type {OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    userId: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
    /**
     * 
     * @type {OBPv600UpdateRateLimitsRequestPropertiesFromDate}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    dateExpires: OBPv600UpdateRateLimitsRequestPropertiesFromDate;
    /**
     * 
     * @type {OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName}
     * @memberof OBPv400CreateDirectDebitRequestProperties
     */
    counterpartyId: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
}

/**
 * Check if a given object implements the OBPv400CreateDirectDebitRequestProperties interface.
 */
export function instanceOfOBPv400CreateDirectDebitRequestProperties(value: object): value is OBPv400CreateDirectDebitRequestProperties {
    if (!('dateStarts' in value) || value['dateStarts'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('dateSigned' in value) || value['dateSigned'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('dateExpires' in value) || value['dateExpires'] === undefined) return false;
    if (!('counterpartyId' in value) || value['counterpartyId'] === undefined) return false;
    return true;
}

export function OBPv400CreateDirectDebitRequestPropertiesFromJSON(json: any): OBPv400CreateDirectDebitRequestProperties {
    return OBPv400CreateDirectDebitRequestPropertiesFromJSONTyped(json, false);
}

export function OBPv400CreateDirectDebitRequestPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv400CreateDirectDebitRequestProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'dateStarts': OBPv600UpdateRateLimitsRequestPropertiesFromDateFromJSON(json['date_starts']),
        'customerId': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameFromJSON(json['customer_id']),
        'dateSigned': OBPv600UpdateRateLimitsRequestPropertiesFromDateFromJSON(json['date_signed']),
        'userId': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameFromJSON(json['user_id']),
        'dateExpires': OBPv600UpdateRateLimitsRequestPropertiesFromDateFromJSON(json['date_expires']),
        'counterpartyId': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameFromJSON(json['counterparty_id']),
    };
}

export function OBPv400CreateDirectDebitRequestPropertiesToJSON(json: any): OBPv400CreateDirectDebitRequestProperties {
    return OBPv400CreateDirectDebitRequestPropertiesToJSONTyped(json, false);
}

export function OBPv400CreateDirectDebitRequestPropertiesToJSONTyped(value?: OBPv400CreateDirectDebitRequestProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_starts': OBPv600UpdateRateLimitsRequestPropertiesFromDateToJSON(value['dateStarts']),
        'customer_id': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameToJSON(value['customerId']),
        'date_signed': OBPv600UpdateRateLimitsRequestPropertiesFromDateToJSON(value['dateSigned']),
        'user_id': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameToJSON(value['userId']),
        'date_expires': OBPv600UpdateRateLimitsRequestPropertiesFromDateToJSON(value['dateExpires']),
        'counterparty_id': OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagNameToJSON(value['counterpartyId']),
    };
}

