/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsProperties } from './OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsProperties';
import {
    OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesFromJSON,
    OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesFromJSONTyped,
    OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesToJSON,
    OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesToJSONTyped,
} from './OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsProperties';

/**
 * 
 * @export
 * @interface OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems
 */
export interface OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems {
    /**
     * 
     * @type {string}
     * @memberof OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems
     */
    type: string;
    /**
     * 
     * @type {OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsProperties}
     * @memberof OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems
     */
    properties: OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsProperties;
}

/**
 * Check if a given object implements the OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems interface.
 */
export function instanceOfOBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems(value: object): value is OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsFromJSON(json: any): OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems {
    return OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsFromJSONTyped(json, false);
}

export function OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'properties': OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesFromJSON(json['properties']),
    };
}

export function OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsToJSON(json: any): OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems {
    return OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsToJSONTyped(json, false);
}

export function OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsToJSONTyped(value?: OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'properties': OBPv600GetWebUiProps200ResponsePropertiesWebuiPropsItemsPropertiesToJSON(value['properties']),
    };
}

