/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv600ResetPasswordComplete200ResponseProperties } from './OBPv600ResetPasswordComplete200ResponseProperties';
import {
    OBPv600ResetPasswordComplete200ResponsePropertiesFromJSON,
    OBPv600ResetPasswordComplete200ResponsePropertiesFromJSONTyped,
    OBPv600ResetPasswordComplete200ResponsePropertiesToJSON,
    OBPv600ResetPasswordComplete200ResponsePropertiesToJSONTyped,
} from './OBPv600ResetPasswordComplete200ResponseProperties';

/**
 * 
 * @export
 * @interface OBPv600ResetPasswordComplete200Response
 */
export interface OBPv600ResetPasswordComplete200Response {
    /**
     * 
     * @type {string}
     * @memberof OBPv600ResetPasswordComplete200Response
     */
    type: string;
    /**
     * 
     * @type {OBPv600ResetPasswordComplete200ResponseProperties}
     * @memberof OBPv600ResetPasswordComplete200Response
     */
    properties: OBPv600ResetPasswordComplete200ResponseProperties;
}

/**
 * Check if a given object implements the OBPv600ResetPasswordComplete200Response interface.
 */
export function instanceOfOBPv600ResetPasswordComplete200Response(value: object): value is OBPv600ResetPasswordComplete200Response {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function OBPv600ResetPasswordComplete200ResponseFromJSON(json: any): OBPv600ResetPasswordComplete200Response {
    return OBPv600ResetPasswordComplete200ResponseFromJSONTyped(json, false);
}

export function OBPv600ResetPasswordComplete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv600ResetPasswordComplete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'properties': OBPv600ResetPasswordComplete200ResponsePropertiesFromJSON(json['properties']),
    };
}

export function OBPv600ResetPasswordComplete200ResponseToJSON(json: any): OBPv600ResetPasswordComplete200Response {
    return OBPv600ResetPasswordComplete200ResponseToJSONTyped(json, false);
}

export function OBPv600ResetPasswordComplete200ResponseToJSONTyped(value?: OBPv600ResetPasswordComplete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'properties': OBPv600ResetPasswordComplete200ResponsePropertiesToJSON(value['properties']),
    };
}

