/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv510GetUserLockStatus200ResponseProperties } from './OBPv510GetUserLockStatus200ResponseProperties';
import {
    OBPv510GetUserLockStatus200ResponsePropertiesFromJSON,
    OBPv510GetUserLockStatus200ResponsePropertiesFromJSONTyped,
    OBPv510GetUserLockStatus200ResponsePropertiesToJSON,
    OBPv510GetUserLockStatus200ResponsePropertiesToJSONTyped,
} from './OBPv510GetUserLockStatus200ResponseProperties';

/**
 * 
 * @export
 * @interface OBPv510GetUserLockStatus200Response
 */
export interface OBPv510GetUserLockStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof OBPv510GetUserLockStatus200Response
     */
    type: string;
    /**
     * 
     * @type {OBPv510GetUserLockStatus200ResponseProperties}
     * @memberof OBPv510GetUserLockStatus200Response
     */
    properties: OBPv510GetUserLockStatus200ResponseProperties;
}

/**
 * Check if a given object implements the OBPv510GetUserLockStatus200Response interface.
 */
export function instanceOfOBPv510GetUserLockStatus200Response(value: object): value is OBPv510GetUserLockStatus200Response {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function OBPv510GetUserLockStatus200ResponseFromJSON(json: any): OBPv510GetUserLockStatus200Response {
    return OBPv510GetUserLockStatus200ResponseFromJSONTyped(json, false);
}

export function OBPv510GetUserLockStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv510GetUserLockStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'properties': OBPv510GetUserLockStatus200ResponsePropertiesFromJSON(json['properties']),
    };
}

export function OBPv510GetUserLockStatus200ResponseToJSON(json: any): OBPv510GetUserLockStatus200Response {
    return OBPv510GetUserLockStatus200ResponseToJSONTyped(json, false);
}

export function OBPv510GetUserLockStatus200ResponseToJSONTyped(value?: OBPv510GetUserLockStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'properties': OBPv510GetUserLockStatus200ResponsePropertiesToJSON(value['properties']),
    };
}

