/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OBPv600GetConnectors200ResponsePropertiesConnectors } from './OBPv600GetConnectors200ResponsePropertiesConnectors';
import {
    OBPv600GetConnectors200ResponsePropertiesConnectorsFromJSON,
    OBPv600GetConnectors200ResponsePropertiesConnectorsFromJSONTyped,
    OBPv600GetConnectors200ResponsePropertiesConnectorsToJSON,
    OBPv600GetConnectors200ResponsePropertiesConnectorsToJSONTyped,
} from './OBPv600GetConnectors200ResponsePropertiesConnectors';

/**
 * 
 * @export
 * @interface OBPv600GetConnectors200ResponseProperties
 */
export interface OBPv600GetConnectors200ResponseProperties {
    /**
     * 
     * @type {OBPv600GetConnectors200ResponsePropertiesConnectors}
     * @memberof OBPv600GetConnectors200ResponseProperties
     */
    connectors: OBPv600GetConnectors200ResponsePropertiesConnectors;
}

/**
 * Check if a given object implements the OBPv600GetConnectors200ResponseProperties interface.
 */
export function instanceOfOBPv600GetConnectors200ResponseProperties(value: object): value is OBPv600GetConnectors200ResponseProperties {
    if (!('connectors' in value) || value['connectors'] === undefined) return false;
    return true;
}

export function OBPv600GetConnectors200ResponsePropertiesFromJSON(json: any): OBPv600GetConnectors200ResponseProperties {
    return OBPv600GetConnectors200ResponsePropertiesFromJSONTyped(json, false);
}

export function OBPv600GetConnectors200ResponsePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OBPv600GetConnectors200ResponseProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'connectors': OBPv600GetConnectors200ResponsePropertiesConnectorsFromJSON(json['connectors']),
    };
}

export function OBPv600GetConnectors200ResponsePropertiesToJSON(json: any): OBPv600GetConnectors200ResponseProperties {
    return OBPv600GetConnectors200ResponsePropertiesToJSONTyped(json, false);
}

export function OBPv600GetConnectors200ResponsePropertiesToJSONTyped(value?: OBPv600GetConnectors200ResponseProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectors': OBPv600GetConnectors200ResponsePropertiesConnectorsToJSON(value['connectors']),
    };
}

