/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using OpenBankProject.Api;
using OpenBankProject.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace OpenBankProject.Test.Api
{
    /// <summary>
    ///  Class for testing DirectoryApi
    /// </summary>
    public sealed class DirectoryApiTests : ApiTestsBase
    {
        private readonly IDirectoryApi _instance;

        public DirectoryApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDirectoryApi>();
        }

        /// <summary>
        /// Test OBPv510CreateConsumerDynamicRegistration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510CreateConsumerDynamicRegistrationAsyncTest()
        {
            OBPv510CreateConsumerDynamicRegistrationRequest oBPv510CreateConsumerDynamicRegistrationRequest = default!;
            var response = await _instance.OBPv510CreateConsumerDynamicRegistrationAsync(oBPv510CreateConsumerDynamicRegistrationRequest);
            var model = response.Ok();
            Assert.IsType<OBPv510UpdateConsumerName200Response>(model);
        }

        /// <summary>
        /// Test OBPv510CreateRegulatedEntity
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510CreateRegulatedEntityAsyncTest()
        {
            OBPv510CreateRegulatedEntityRequest oBPv510CreateRegulatedEntityRequest = default!;
            var response = await _instance.OBPv510CreateRegulatedEntityAsync(oBPv510CreateRegulatedEntityRequest);
            var model = response.Ok();
            Assert.IsType<OBPv510GetRegulatedEntityById200Response>(model);
        }

        /// <summary>
        /// Test OBPv510CreateRegulatedEntityAttribute
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510CreateRegulatedEntityAttributeAsyncTest()
        {
            string regulatedentityid = default!;
            OBPv510UpdateRegulatedEntityAttributeRequest oBPv510UpdateRegulatedEntityAttributeRequest = default!;
            var response = await _instance.OBPv510CreateRegulatedEntityAttributeAsync(regulatedentityid, oBPv510UpdateRegulatedEntityAttributeRequest);
            var model = response.Ok();
            Assert.IsType<OBPv510GetRegulatedEntityAttributeById200Response>(model);
        }

        /// <summary>
        /// Test OBPv510DeleteRegulatedEntity
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510DeleteRegulatedEntityAsyncTest()
        {
            string regulatedentityid = default!;
            await _instance.OBPv510DeleteRegulatedEntityAsync(regulatedentityid);
        }

        /// <summary>
        /// Test OBPv510DeleteRegulatedEntityAttribute
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510DeleteRegulatedEntityAttributeAsyncTest()
        {
            string regulatedentityid = default!;
            string regulatedentityattributeid = default!;
            await _instance.OBPv510DeleteRegulatedEntityAttributeAsync(regulatedentityid, regulatedentityattributeid);
        }

        /// <summary>
        /// Test OBPv510GetAllRegulatedEntityAttributes
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510GetAllRegulatedEntityAttributesAsyncTest()
        {
            string regulatedentityid = default!;
            var response = await _instance.OBPv510GetAllRegulatedEntityAttributesAsync(regulatedentityid);
            var model = response.Ok();
            Assert.IsType<OBPv510GetAllRegulatedEntityAttributes200Response>(model);
        }

        /// <summary>
        /// Test OBPv510GetRegulatedEntityAttributeById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510GetRegulatedEntityAttributeByIdAsyncTest()
        {
            string regulatedentityid = default!;
            string regulatedentityattributeid = default!;
            var response = await _instance.OBPv510GetRegulatedEntityAttributeByIdAsync(regulatedentityid, regulatedentityattributeid);
            var model = response.Ok();
            Assert.IsType<OBPv510GetRegulatedEntityAttributeById200Response>(model);
        }

        /// <summary>
        /// Test OBPv510GetRegulatedEntityById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510GetRegulatedEntityByIdAsyncTest()
        {
            string regulatedentityid = default!;
            var response = await _instance.OBPv510GetRegulatedEntityByIdAsync(regulatedentityid);
            var model = response.Ok();
            Assert.IsType<OBPv510GetRegulatedEntityById200Response>(model);
        }

        /// <summary>
        /// Test OBPv510RegulatedEntities
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510RegulatedEntitiesAsyncTest()
        {
            var response = await _instance.OBPv510RegulatedEntitiesAsync();
            var model = response.Ok();
            Assert.IsType<OBPv510RegulatedEntities200Response>(model);
        }

        /// <summary>
        /// Test OBPv510UpdateRegulatedEntityAttribute
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OBPv510UpdateRegulatedEntityAttributeAsyncTest()
        {
            string regulatedentityid = default!;
            string regulatedentityattributeid = default!;
            OBPv510UpdateRegulatedEntityAttributeRequest oBPv510UpdateRegulatedEntityAttributeRequest = default!;
            var response = await _instance.OBPv510UpdateRegulatedEntityAttributeAsync(regulatedentityid, regulatedentityattributeid, oBPv510UpdateRegulatedEntityAttributeRequest);
            var model = response.Ok();
            Assert.IsType<OBPv510GetRegulatedEntityAttributeById200Response>(model);
        }
    }
}
