/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpProperties {
    #[serde(rename = "sunday")]
    pub sunday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "tuesday")]
    pub tuesday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "wednesday")]
    pub wednesday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "monday")]
    pub monday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "friday")]
    pub friday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "thursday")]
    pub thursday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
    #[serde(rename = "saturday")]
    pub saturday: Box<models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday>,
}

impl Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpProperties {
    pub fn new(sunday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, tuesday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, wednesday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, monday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, friday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, thursday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday, saturday: models::Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpPropertiesSunday) -> Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpProperties {
        Obpv300GetBranches200ResponsePropertiesBranchesItemsPropertiesDriveUpProperties {
            sunday: Box::new(sunday),
            tuesday: Box::new(tuesday),
            wednesday: Box::new(wednesday),
            monday: Box::new(monday),
            friday: Box::new(friday),
            thursday: Box::new(thursday),
            saturday: Box::new(saturday),
        }
    }
}

