<?php
/**
 * OBPv310SaveHistoricalTransaction200ResponseProperties
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenBankProject
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenBankProject\Model;

use \ArrayAccess;
use \OpenBankProject\ObjectSerializer;

/**
 * OBPv310SaveHistoricalTransaction200ResponseProperties Class Doc Comment
 *
 * @category Class
 * @package  OpenBankProject
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OBPv310SaveHistoricalTransaction200ResponseProperties implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OBPv3_1_0_saveHistoricalTransaction_200_response_properties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'description' => '\OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName',
        'to' => '\OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo',
        'transaction_id' => '\OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName',
        'transaction_request_type' => '\OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName',
        'completed' => '\OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate',
        'charge_policy' => '\OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName',
        'from' => '\OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo',
        'value' => '\OpenBankProject\Model\OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit',
        'posted' => '\OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'description' => null,
        'to' => null,
        'transaction_id' => null,
        'transaction_request_type' => null,
        'completed' => null,
        'charge_policy' => null,
        'from' => null,
        'value' => null,
        'posted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'description' => false,
        'to' => false,
        'transaction_id' => false,
        'transaction_request_type' => false,
        'completed' => false,
        'charge_policy' => false,
        'from' => false,
        'value' => false,
        'posted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'description' => 'description',
        'to' => 'to',
        'transaction_id' => 'transaction_id',
        'transaction_request_type' => 'transaction_request_type',
        'completed' => 'completed',
        'charge_policy' => 'charge_policy',
        'from' => 'from',
        'value' => 'value',
        'posted' => 'posted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'description' => 'setDescription',
        'to' => 'setTo',
        'transaction_id' => 'setTransactionId',
        'transaction_request_type' => 'setTransactionRequestType',
        'completed' => 'setCompleted',
        'charge_policy' => 'setChargePolicy',
        'from' => 'setFrom',
        'value' => 'setValue',
        'posted' => 'setPosted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'description' => 'getDescription',
        'to' => 'getTo',
        'transaction_id' => 'getTransactionId',
        'transaction_request_type' => 'getTransactionRequestType',
        'completed' => 'getCompleted',
        'charge_policy' => 'getChargePolicy',
        'from' => 'getFrom',
        'value' => 'getValue',
        'posted' => 'getPosted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('transaction_request_type', $data ?? [], null);
        $this->setIfExists('completed', $data ?? [], null);
        $this->setIfExists('charge_policy', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('posted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['transaction_id'] === null) {
            $invalidProperties[] = "'transaction_id' can't be null";
        }
        if ($this->container['transaction_request_type'] === null) {
            $invalidProperties[] = "'transaction_request_type' can't be null";
        }
        if ($this->container['completed'] === null) {
            $invalidProperties[] = "'completed' can't be null";
        }
        if ($this->container['charge_policy'] === null) {
            $invalidProperties[] = "'charge_policy' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['value'] === null) {
            $invalidProperties[] = "'value' can't be null";
        }
        if ($this->container['posted'] === null) {
            $invalidProperties[] = "'posted' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets description
     *
     * @return \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo $to to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName $transaction_id transaction_id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets transaction_request_type
     *
     * @return \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
     */
    public function getTransactionRequestType()
    {
        return $this->container['transaction_request_type'];
    }

    /**
     * Sets transaction_request_type
     *
     * @param \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName $transaction_request_type transaction_request_type
     *
     * @return self
     */
    public function setTransactionRequestType($transaction_request_type)
    {
        if (is_null($transaction_request_type)) {
            throw new \InvalidArgumentException('non-nullable transaction_request_type cannot be null');
        }
        $this->container['transaction_request_type'] = $transaction_request_type;

        return $this;
    }

    /**
     * Gets completed
     *
     * @return \OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate
     */
    public function getCompleted()
    {
        return $this->container['completed'];
    }

    /**
     * Sets completed
     *
     * @param \OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate $completed completed
     *
     * @return self
     */
    public function setCompleted($completed)
    {
        if (is_null($completed)) {
            throw new \InvalidArgumentException('non-nullable completed cannot be null');
        }
        $this->container['completed'] = $completed;

        return $this;
    }

    /**
     * Gets charge_policy
     *
     * @return \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName
     */
    public function getChargePolicy()
    {
        return $this->container['charge_policy'];
    }

    /**
     * Sets charge_policy
     *
     * @param \OpenBankProject\Model\OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName $charge_policy charge_policy
     *
     * @return self
     */
    public function setChargePolicy($charge_policy)
    {
        if (is_null($charge_policy)) {
            throw new \InvalidArgumentException('non-nullable charge_policy cannot be null');
        }
        $this->container['charge_policy'] = $charge_policy;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \OpenBankProject\Model\OBPv310SaveHistoricalTransactionRequestPropertiesTo $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets value
     *
     * @return \OpenBankProject\Model\OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param \OpenBankProject\Model\OBPv500GetMyCustomersAtBank200ResponsePropertiesCustomersItemsPropertiesCreditLimit $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets posted
     *
     * @return \OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate
     */
    public function getPosted()
    {
        return $this->container['posted'];
    }

    /**
     * Sets posted
     *
     * @param \OpenBankProject\Model\OBPv600UpdateRateLimitsRequestPropertiesFromDate $posted posted
     *
     * @return self
     */
    public function setPosted($posted)
    {
        if (is_null($posted)) {
            throw new \InvalidArgumentException('non-nullable posted cannot be null');
        }
        $this->container['posted'] = $posted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


