/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
import com.openbankproject.model.OBPv510GetMyConsentsByBank200ResponsePropertiesConsentsItemsPropertiesJwtPayloadPropertiesViewsItems;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OBPv500GetConsentByConsentRequestId200ResponseProperties
 */
class OBPv500GetConsentByConsentRequestId200ResponsePropertiesTest {
    private final OBPv500GetConsentByConsentRequestId200ResponseProperties model = new OBPv500GetConsentByConsentRequestId200ResponseProperties();

    /**
     * Model tests for OBPv500GetConsentByConsentRequestId200ResponseProperties
     */
    @Test
    void testOBPv500GetConsentByConsentRequestId200ResponseProperties() {
        // TODO: test OBPv500GetConsentByConsentRequestId200ResponseProperties
    }

    /**
     * Test the property 'jwt'
     */
    @Test
    void jwtTest() {
        // TODO: test jwt
    }

    /**
     * Test the property 'accountAccess'
     */
    @Test
    void accountAccessTest() {
        // TODO: test accountAccess
    }

    /**
     * Test the property 'consentRequestId'
     */
    @Test
    void consentRequestIdTest() {
        // TODO: test consentRequestId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'consentId'
     */
    @Test
    void consentIdTest() {
        // TODO: test consentId
    }

}
