/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.OBPv310GetMeeting200ResponsePropertiesCreator;
import com.openbankproject.model.OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties
 */
class OBPv310GetMeeting200ResponsePropertiesInviteesItemsPropertiesTest {
    private final OBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties model = new OBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties();

    /**
     * Model tests for OBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties
     */
    @Test
    void testOBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties() {
        // TODO: test OBPv310GetMeeting200ResponsePropertiesInviteesItemsProperties
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'contactDetails'
     */
    @Test
    void contactDetailsTest() {
        // TODO: test contactDetails
    }

}
