/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-22T07:16:47.250257  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenBankProject.Model;
using OpenBankProject.Client;
using System.Reflection;

namespace OpenBankProject.Test.Model
{
    /// <summary>
    ///  Class for testing OBPv600CreateTransactionRequestCardanoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OBPv600CreateTransactionRequestCardanoRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OBPv600CreateTransactionRequestCardanoRequest
        //private OBPv600CreateTransactionRequestCardanoRequest instance;

        public OBPv600CreateTransactionRequestCardanoRequestTests()
        {
            // TODO uncomment below to create an instance of OBPv600CreateTransactionRequestCardanoRequest
            //instance = new OBPv600CreateTransactionRequestCardanoRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OBPv600CreateTransactionRequestCardanoRequest
        /// </summary>
        [Fact]
        public void OBPv600CreateTransactionRequestCardanoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OBPv600CreateTransactionRequestCardanoRequest
            //Assert.IsType<OBPv600CreateTransactionRequestCardanoRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
    }
}
