/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.OBPv600GetAbacRuleSchema200ResponsePropertiesParameters
import com.openbankproject.models.OBPv600GetAbacRuleSchema200ResponsePropertiesParametersItems

class OBPv600GetAbacRuleSchema200ResponsePropertiesParametersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OBPv600GetAbacRuleSchema200ResponsePropertiesParameters
        //val modelInstance = OBPv600GetAbacRuleSchema200ResponsePropertiesParameters()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
