/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.OBPv510GetConsumers200ResponseProperties
import com.openbankproject.models.OBPv510GetConsumers200ResponsePropertiesConsumers

class OBPv510GetConsumers200ResponsePropertiesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OBPv510GetConsumers200ResponseProperties
        //val modelInstance = OBPv510GetConsumers200ResponseProperties()

        // to test the property `consumers`
        should("test consumers") {
            // uncomment below to test the property
            //modelInstance.consumers shouldBe ("TODO")
        }

    }
}
