/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.OBPv300GetBranches200ResponsePropertiesBranchesItems
import com.openbankproject.models.OBPv300GetBranches200ResponsePropertiesBranchesItemsProperties

class OBPv300GetBranches200ResponsePropertiesBranchesItemsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OBPv300GetBranches200ResponsePropertiesBranchesItems
        //val modelInstance = OBPv300GetBranches200ResponsePropertiesBranchesItems()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `properties`
        should("test properties") {
            // uncomment below to test the property
            //modelInstance.properties shouldBe ("TODO")
        }

    }
}
