/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param example 
 */


data class OBPv400GetDynamicEndpoints200ResponsePropertiesDynamicEndpointsItemsPropertiesSwaggerStringPropertiesDefinitionsPropertiesAccountNamePropertiesPropertiesPropertiesNameProperties (

    @Json(name = "type")
    val type: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName,

    @Json(name = "example")
    val example: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName

) {


}

