/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesAccounts
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesAtms
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesBanks
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesBranches
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesCrmEvents
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesProducts
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesTransactions
import com.openbankproject.models.OBPv210SandboxDataImportRequestPropertiesUsers

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param crmEvents 
 * @param users 
 * @param products 
 * @param banks 
 * @param branches 
 * @param transactions 
 * @param accounts 
 * @param atms 
 */


data class OBPv210SandboxDataImportRequestProperties (

    @Json(name = "crm_events")
    val crmEvents: OBPv210SandboxDataImportRequestPropertiesCrmEvents,

    @Json(name = "users")
    val users: OBPv210SandboxDataImportRequestPropertiesUsers,

    @Json(name = "products")
    val products: OBPv210SandboxDataImportRequestPropertiesProducts,

    @Json(name = "banks")
    val banks: OBPv210SandboxDataImportRequestPropertiesBanks,

    @Json(name = "branches")
    val branches: OBPv210SandboxDataImportRequestPropertiesBranches,

    @Json(name = "transactions")
    val transactions: OBPv210SandboxDataImportRequestPropertiesTransactions,

    @Json(name = "accounts")
    val accounts: OBPv210SandboxDataImportRequestPropertiesAccounts,

    @Json(name = "atms")
    val atms: OBPv210SandboxDataImportRequestPropertiesAtms

) {


}

