/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.OBPv310GetMethodRoutings200ResponsePropertiesMethodRoutings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param methodRoutings 
 */


data class OBPv310GetMethodRoutings200ResponseProperties (

    @Json(name = "method_routings")
    val methodRoutings: OBPv310GetMethodRoutings200ResponsePropertiesMethodRoutings

) {


}

