/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.OBPv310Config200ResponsePropertiesAkka
import com.openbankproject.models.OBPv310Config200ResponsePropertiesCache
import com.openbankproject.models.OBPv310Config200ResponsePropertiesElasticSearch
import com.openbankproject.models.OBPv310Config200ResponsePropertiesScopes

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param elasticSearch 
 * @param scopes 
 * @param akka 
 * @param cache 
 */


data class OBPv310Config200ResponseProperties (

    @Json(name = "elastic_search")
    val elasticSearch: OBPv310Config200ResponsePropertiesElasticSearch,

    @Json(name = "scopes")
    val scopes: OBPv310Config200ResponsePropertiesScopes,

    @Json(name = "akka")
    val akka: OBPv310Config200ResponsePropertiesAkka,

    @Json(name = "cache")
    val cache: OBPv310Config200ResponsePropertiesCache

) {


}

