/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param imageURL 
 */


data class OBPv121UpdateCounterpartyImageUrlRequestProperties (

    @Json(name = "image_URL")
    val imageURL: OBPv400UpdateSystemLevelEndpointTagRequestPropertiesTagName

) {


}

