/*
Open Bank Project API v6.0.0

Testing JSONSchemaValidationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package obp

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_obp_JSONSchemaValidationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test JSONSchemaValidationAPIService OBPv400CreateJsonSchemaValidation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var operationid string

		resp, httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400CreateJsonSchemaValidation(context.Background(), operationid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JSONSchemaValidationAPIService OBPv400DeleteJsonSchemaValidation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var operationid string

		httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400DeleteJsonSchemaValidation(context.Background(), operationid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JSONSchemaValidationAPIService OBPv400GetAllJsonSchemaValidations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400GetAllJsonSchemaValidations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JSONSchemaValidationAPIService OBPv400GetAllJsonSchemaValidationsPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400GetAllJsonSchemaValidationsPublic(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JSONSchemaValidationAPIService OBPv400GetJsonSchemaValidation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var operationid string

		resp, httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400GetJsonSchemaValidation(context.Background(), operationid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JSONSchemaValidationAPIService OBPv400UpdateJsonSchemaValidation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var operationid string

		resp, httpRes, err := apiClient.JSONSchemaValidationAPI.OBPv400UpdateJsonSchemaValidation(context.Background(), operationid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
